### ISSUE TITLE
[Quest 13142][Minor] Banshees revenge - Missing RP

### ISSUE THREAD

**Issue by disruption01** [gamefreedomgit/Frostmourne#1008]
https://www.wowhead.com/wotlk/quest=13142/banshees-revenge

this quest is missing the RP, it's a minor issue but still worth mentioning :)

**Comment by disruption01** [comment]
another issue I found is that Overthane Balargarde can be fear spammed making this quest way more trivial than it should. (I think it's missing other immunities aswell)

**Comment by WhitemaneChronus** [comment]
Overthane Balargarde NPC on this quest after summoning is stuck under texture. The RP bugs out and NPC stays under ground and is not attackable. 
either player cannot start it because it already exists but not visible, or during the RP both lich king and this npc vanish. 

resetting the encounter once or twice (requires a GM) will fix the issue.
