### ISSUE TITLE
Gothik the harvester reset bug 

### ISSUE THREAD

**Issue by hamajaxd** [gamefreedomgit/Frostmourne#1069]
Gothik the harvester reset bug 

For unknown reason sometimes he just reset the fight on his own first run on 25 man he resetted as soon as the gate opened but today i have done it in 10 man and he reseted 10 sec before he tps so i dunno whats causing the exact problem and how to fix

**Comment by Godmatik** [comment]
Have seen it before once also.

We think it occurs when the person who pulls the boss at start dies sometime in the fight, he resets right after. So sounds like Gothik is not properly entering combat with everyone on pull.

**Comment by Galatoa** [comment]
It might have to something to do with the boss building aggro before it teleports down and not being able to "attack" the person that is at the top of the threat chart.
Since u can't attack the boss it's probably the healers that have the aggro if that is happening and the fight reset happened to us with holy palas using bubble to holy wrath ads when the gates opened.
Maybe unrelated but worth considering.

**Comment by Afgann** [comment]
fixed
