### ISSUE TITLE
Frost Lotus missing from icethorn and lichbloom loot table

### ISSUE THREAD

**Issue by iskense** [gamefreedomgit/Frostmourne#1107]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
As an herbalist, frost lotus should be loot from any herb in northrend. while some does, i farm over 400 icerthorn and lichbloom without seeing a drop.

**How to reproduce:**
gather icethorn and lichbloom

**How it should work:**
frost lotus doesnt have high drop rate, but after 400 of each i should have seen some.

**Database links:**

https://www.wowhead.com/wotlk/item=36908/frost-lotus#gathered-from-object

**Comment by zuldabad** [comment]
wierd, cos yesterday i gather x3 frost lotus from one icethorn

**Comment by iskense** [comment]
Yesterday I didn't get any and today I get a normal amount

**Comment by iskense** [comment]
i did farm 6h+ yesterday without getting a single one this is why i did th ereport. unsure if maybe they fix it or the drop rate wasnt good.

**Comment by LezChap** [comment]
I've gotten one or two frost lotus from the high level herbs, but it seems to be a very poor rate compared to the lower level herbs, where I've gotten roughly 2-3x as many.  I don't know if my sample size is large enough to determine anything, but the RNG does feel "off".

**Comment by Riztazz** [comment]
The drop rate is too low across all herbs, should be 7.5% instead of 5%.
Both lichbloom and icethorn also had 5% chance to drop a lotus, there is no unlucky prevention when it comes to herbs so sadly you were just.. out of luck. Gonna fix lotus droprate across all northrend herbs

https://wowpedia.fandom.com/wiki/Frost_Lotus
Hotfix (2010-02-18): The drop rate of Frost Lotus, from herbs in Northrend, has been increased by 50%. From 5% to 7.5%
