### ISSUE TITLE
DK. Army of the Dead  2 bugs.

### ISSUE THREAD

**Issue by wotlkenjoyer** [gamefreedomgit/Frostmourne#118]
**Description:**
1. Army of  the dead can be hyperspawned , potentially can crash the server with many dks.
2. Army of the dead stays neutral/AFK during dueling, refuse to attack my duel target.

**How to reproduce:**
[Army stays AFK youtube video](https://www.youtube.com/watch?v=qgdEtaUS09o)

[Army hyperspawn youtube video](https://www.youtube.com/watch?v=58r74Ji9x9g)

Hyperspawning happens because of cooldown reset  each duel. Probably same can be done with reseting a boss encounter (when he going evade and resets)

**Comment by Manpower99** [comment]
The spell currently has a couple of issues, for instance when you command an unholy death knight's permanent ghoul to attack through an ability or /startattack, the army attacks after the permanent ghoul hits, instead of at the exact same time the command.
leaping seems to be an issue aswell with not all of them leaping.
Army/Gargoyle/Permanent Ghoul as unholy always should attack and target the same target and follow the same commands on activation not on hit.

**Comment by Afgann** [comment]
fixed
