### ISSUE TITLE
Jenkins Achievement Currently Impossible

### ISSUE THREAD

**Issue by TheGreatTesla** [gamefreedomgit/Frostmourne#1195]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Blackhand Incarcerators in Blackrock Spire are untargetable and unkillable rendering the Jenkins achievement and access to the rest of the instance impossible. Even clearing the mobs in the previous room and clicking the altar does not make them targetable. The door is locked and only passable if the boss is killed.

**How to reproduce:**
Go to Upper Blackrock Spire and try to attack the mobs.

**How it should work:**
Mobs should be killable after door is opened, but since door is already opened the mobs should either be targetable from the start or at least require the runes they are standing on to be activated by killing the trash mobs in the previous room. Also ensure that clearing these mobs fixes the Altar to summon the boss, as the altar seems to only channel for a few seconds and then stop as it currently stands. Not sure if this is because the Incarcerators are still there or because the Altar does not work at all.

Easiest fix is to just leave the door after Pyroguard Emberseer open but not sure if that breaks anything further in the instance.

**Database links:**
https://www.wowhead.com/classic/npc=10316/blackhand-incarcerator
https://www.wowhead.com/classic/npc=9816/pyroguard-emberseer
https://www.wowhead.com/achievement=9058/leeeeeeeeeeeeeroy

**Comment by yeagerca** [comment]
The real issue is that Pyroguard Emberseer's ritual requires three players to interact with it to begin the summoning instead of one player. It was changed to one player in patch 3.0.8.
Blue Post: https://www.bluetracker.gg/wow/topic/us-en/100501234-can-we-change-ubrs-blackrock-altar/
Full (Undocumented) Patch changes: https://wowpedia.fandom.com/wiki/Patch_3.0.8_(undocumented_changes)#Dungeons_and_Raids

The Jenkins achievement works fine, only the process of getting there is bugged.
![image](https://github.com/gamefreedomgit/Frostmourne/assets/93017663/1a335afb-8097-4c3e-b2ad-73a3d13db6e4)


Checklist based on the Blue Post
Works:
- You no longer need quintessence to summon Majordomo Executus.
- You no longer need the Mallet of Zul'Farrak to summon Gahz'rilla.
- Nightbane is also being made accessible without the urn.

Needs fixing:
- The ritual objects that used to require 3 players to activate in Blackrock Spire and Uldaman now only require 1.

I don't know:
- You no longer need the Scepter of Celebras to teleport to the final section of Maraudon.
- The Scepter and Mallet both turn into actual weapons. 
- The change to the Mallet and Scepter into weapons will also change the existing items.

**Comment by Piootrek** [comment]
It works correctly. The ritual requires only 1 player.
