### ISSUE TITLE
[DK] Sigil of the Wild Buck

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1242]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** DMG addition seems wrong in testing. Dmg increase is exactly 160. Without it DC hit for 875 with no modifiers, talents etc, with it dmg was 1035. 875 - 1035 = - 160 -> which is double the amount it should be. 

**How to reproduce:** Cast DC without the item, then cast it with it equipped. Calculate the difference.

**How it should work:** It should give 80 dmg increase to base dmg before modifiers. Checking the item in DB doesn't show any extra hidden effects.

**Database links:** https://www.wowhead.com/wotlk/spell=54807/increased-death-coil-damage

**Comment by Sylanha** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/172520001/725ec305-4f5d-4e15-a43d-bcd32f16f38d)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/172520001/31b5ea33-613f-4c31-896c-eabb82dbd856)

You can clearly see that you have to precisely pay attention to what the tooltip means with "increasing damage dealt by" or "increasing BASE damage dealt by".

> **How it should work:** It should give 80 dmg increase to base dmg before modifiers. Checking the item in DB doesn't show any extra hidden effects.

No, it works perfectly fine, since it is not supposed to increase the base damage. There are sigils that do exactly that (for example Sigil of Awareness), and it is also saying it in the tooltip if they actually increase the BASE damage. 
So this report is invalid.

**Comment by haephaistoss** [comment]
The tooltip in the item description matters is usually of entirely no significance, only for RP purposes.

What matters is the spell or aura it applies and what that aura affects and how.

Either way, giving 160 dmg to the end dmg (=after modifiers) is double of what it should in your reading.

Since providing 80 dmg after modifiers means:

base * modifiers + 80

Even with modifiers it would be too much, in which case it would look like this:

(base + 80) * modifiers.

Blizzard has been pretty inaccurate in terms of tooltips, and the stronger relics in wotlk are usually all upgraded versions of lower quality starting relics, and these are usually base dmg increases.

I have yet to see one that wasn't in og wrath. Be it lightning bolt, divine storm, crusader strike, seal of right, death coil, so on

**Comment by Piootrek** [comment]
Currently it increases basepoints of Death Coil damage spell and damage is calculated using those basepoints. According to the data from the Blizzard files it works correctly. Please provide additional proof if you think it doesn't.
