### ISSUE TITLE
Very high damage from DK army

### ISSUE THREAD

**Issue by Apakalipsis1992** [gamefreedomgit/Frostmourne#1243]
At the moment, DK's army is doing a lot of damage. For comparison, I took an example from the first CD and the CD after 2 weeks. This is what I saw.
In the logs from June 19, the average damage from melee attacks of the army is 128 from normal hits and 271 from crits. On July 3, the same player had an average army damage from normal hits of 227 and from crits of 495. The results doubled.
![19 jun](https://github.com/gamefreedomgit/Frostmourne/assets/52465820/214063c6-dbab-4090-846b-c37f419faaa9)
![03 jul](https://github.com/gamefreedomgit/Frostmourne/assets/52465820/391dd6da-8a85-4f2b-8a7d-ab9c828ba95c)
Too strong an increase in damage, which seems to me to be related not only to gear. Having checked the logs from wow classic, even there I didn’t see that much damage.
Please check what is causing this and if it is a bug, fix it.

**Comment by Apakalipsis1992** [comment]
Even on wow classic army does less damage
![image](https://github.com/gamefreedomgit/Frostmourne/assets/52465820/169bc577-a91a-4a36-87a8-5b397a0d948a)

**Comment by Godmatik** [comment]
Confirmed, the scaling is simply way off

**Comment by Sylanha** [comment]
![image](https://github.com/gamefreedomgit/Frostmourne/assets/172520001/6ec80603-23ea-44f5-839d-e82caedaca3e)

If we are going off classic logs as the ones you just showed , why are you not showing the gargoyle dmg aswell? Which is wrongly artificially nerfed on whitemane right now for no reason. If you go by those numbers of the same log then you should stay consistent and fix army and gargoyle , that would mean if you are looking to have army to deal that amount of dmg as you showed on the log , the same needs to be the case for gargoyle. Its a bit dishonest of you to not show the whole picture with army + gargoyle espechially since you know you were the cause of getting gargoyle nerfed in the first place + you know that gargoyle is wrongly nerfed on whitemane currently.

**Comment by Sylanha** [comment]
@Apakalipsis1992 I will be referring to your Original post here:

![image](https://github.com/gamefreedomgit/Frostmourne/assets/172520001/fb733867-abde-4c3d-9935-d0fede2e5e24)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/172520001/f2f0ceba-de29-4ee8-b0a3-6f91c62e8980)

This is another attempt to be shady and not actually an attempt to fix the class but to artificially nerf unholy for your own benefit. Compared to Spin's gargoyle and classic gargoyle Spin's is doing 136k dmg, while on classic gargoyle did 273kdmg. So that's a solid 137k dmg difference which is basially right now 2x gargoyle summons from Spin compared to  1 summon from classic wotlk unholy player.

1. You forgot to mention that on this ( first picture) the Unholy player pre casted his army , therefore not snapshotting it + losing 25% uptime since he casted it 10 sec before the encounter even started which can be confirmed by the stream vod that has been recorded.
2. This is a log from the 19th June and you are comparing it to the latest 03th July which is a big jump in gear especially since the shown unholy player compared to the first picture is right now almost fully BIS geared with a better kill timer compared to the first picture.
3. As already mentioned above on the 2nd Screenshot the unholy dk actually snapshotted his army, therefore buffing it immensely and not wasting any uptime on it compared to the first screenshot

What we can clearly see here also given the logs from classic wotlk is that army indeed is doing more dmg compared to classic, but gargoyle on the other hand is doing way worse compared to the same log as classic (because it has received a 200 ms delay per shot just recently artificially) you need to be consistent here and fix both issues and not nerf 2x big major CDs of Unholy only because you yourself are playing frost.

**Comment by Apakalipsis1992** [comment]
> @Apakalipsis1992 I will be referring to your Original post here:
> 
> ![image](https://private-user-images.githubusercontent.com/172520001/346339595-fb733867-abde-4c3d-9935-d0fede2e5e24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjAyMjIsIm5iZiI6MTcyMDQxOTkyMiwicGF0aCI6Ii8xNzI1MjAwMDEvMzQ2MzM5NTk1LWZiNzMzODY3LWFiZGUtNGMzZC05OTM1LWQwZmVkZTJlNWUyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwNjI1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZmU1NzUyNWY2OWQyNWFkMjFlOTI2OGZiZTIzMmU3MWMyNjExYWU0OGEwNTVhYzljOWRjMmI2MTYwMDc2YThiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g1TcFpOZ2PJvJO0_lIV9xbmTsLK_zqzGeeOKmLOXX8A) ![image](https://private-user-images.githubusercontent.com/172520001/346339842-f2f0ceba-de29-4ee8-b0a3-6f91c62e8980.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjAyMjIsIm5iZiI6MTcyMDQxOTkyMiwicGF0aCI6Ii8xNzI1MjAwMDEvMzQ2MzM5ODQyLWYyZjBjZWJhLWRlMjktNGVlOC1iMGEzLTZmOTFjNjJlODk4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQwNjI1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTY1MzhjZGYxNWVkNjU4NDYxOGEwMWNiN2FiMDY0MThlZGNkZDZkZmJjNzc3YjEwNzU5MDA4MGYwMmI2MTcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5t6qtk1BmjteWTMV0oDLJL6ea8oVkojzhEe9mlOwUWk)
> 
> This is another attempt to be shady and not actually an attempt to fix the class but to artificially nerf unholy for your own benefit. Compared to Spin's gargoyle and classic gargoyle Spin's is doing 136k dmg, while on classic gargoyle did 273kdmg. So that's a solid 137k dmg difference which is basially right now 2x gargoyle summons from Spin compared to 1 summon from classic wotlk unholy player.
> 
> 1. You forgot to mention that on this ( first picture) the Unholy player pre casted his army , therefore not snapshotting it + losing 25% uptime since he casted it 10 sec before the encounter even started which can be confirmed by the stream vod that has been recorded.
> 2. This is a log from the 19th June and you are comparing it to the latest 03th July which is a big jump in gear especially since the shown unholy player compared to the first picture is right now almost fully BIS geared with a better kill timer compared to the first picture.
> 3. As already mentioned above on the 2nd Screenshot the unholy dk actually snapshotted his army, therefore buffing it immensely and not wasting any uptime on it compared to the first screenshot
> 
> What we can clearly see here also given the logs from classic wotlk is that army indeed is doing more dmg compared to classic, but gargoyle on the other hand is doing way worse compared to the same log as classic (because it has received a 200 ms delay per shot just recently artificially) you need to be consistent here and fix both issues and not nerf 2x big major CDs of Unholy only because you yourself are playing frost.

1. After my report on the weakening (in fact, a return to correct operation as it was on og wow) of the gargoyle, the administrators decided to return it and returned it to work without a dynamic delay between shots (I don’t know where you were looking, I attached a screenshot)
![image](https://github.com/gamefreedomgit/Frostmourne/assets/52465820/a3c13743-479c-4f70-8f33-d907db8b33f2)
After that, they themselves realized that without a delay, a gargoyle is just garbage and they also decided to introduce a static delay of 200 ms, as they originally planned before my intervention, which still works stronger than it did on og wow, I repeat, on wow classic The gargoyle did not work correctly due to a developer error. There is a video confirming that on OG WOW the gargoyle used a dynamic delay between shots.
2. I decided to fix the army because it simply shouldn’t do so much damage and never did, neither on OG WOW nor on WOW classic, and it’s not about how dk is dressed and when he called the army.

![image](https://github.com/gamefreedomgit/Frostmourne/assets/52465820/badd26df-f825-4665-ad8d-0208da8eab74)

**Comment by Sand1dark** [comment]
Apakalipsis you are the most self centered and annoying person i have ever seen. You intentionally try to destroy a spec that is overpowered in p1, you do not try to balance the game. There are enormous ammount of bugs throughout the classes making them much stronger than classic or og wow, yet we see only unholy nerfs ? Goyle was confirmed to be in its normal state a.k.a. no delay, yet we again have delay. They didnt know where was the problem with army, and they came up with the conclusion it was affected by glyph ? What a bunch of nonsense :) . If you find it normal to snapshot 3m cd with all your procs together with a 10m 4 sec cast cd and deal as much dmg as 1 global of a spellhancer you my friend are totally delulu. 
I understqnd you cant stand the spec but you are crossing some boundaries with the terms being normal and being nerfed. 
All classes are stronger than og or classic, but only dk and more specific only unholy is being brought bqck to its "original" state, which is not entirely true. The spec is consisted of those 2 snqps qnd you managed to kill both. Long live fdk :) clown.

**Comment by exodiaxax** [comment]
Are you mostly crying because you can't be on top logs as frost dk or you have something against uh dk because you can't play it so you are trying to intentionally destroy a spec that is made to be good early tiers and it drops down with later tiers, you are clearly most self centred person i saw on this server that is constantly crying to nerf uh dks in every way possible, we are all trying to test stuff and make this game a better place, but you are just constantly crying even tho garg is doing x2 less dmg than it should, you are comparing guy who had pre-bis and now is close to bis in a fight where he poped it before fight, and next week he tested to snapshot it, it was doing more dmg , ofc it would do, do you understand in first place how uh dk's work and how much haste they have in t7 ? Please don't be delusional only because you can't be #1 on logs.

**Comment by Riztazz** [comment]
Army has been heavily changed, is this up to date?
