### ISSUE TITLE
[WARRIOR] Deep Wounds

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1283]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Deep Wounds isn't affected by dmg reduction auras once applied.

**How to reproduce:** Get a crit on anybody and have them use a dmg reduction aura like Shield Wall

**How it should work:** It should be reduced by modifiers once applied. It was bugged in 3.2, and worked like this on Retail, but was fixed later.

**Database links:** https://www.wowhead.com/wotlk/spell=12868/deep-wounds

**Comment by AlucardHellsingChapel** [comment]
Provide more informations about this the database links provide nothing aswell it does not matter if it was bugged in 3.2 as we are on 3.3.5

**Comment by Manpower99** [comment]
@UltraNix https://www.youtube.com/watch?v=YQ12kxgzZxI&t=177s
As you can see after dispersion the dot damage remained the same

> https://wowpedia.fandom.com/wiki/Patch_3.1.0
Deep Wounds :  The damage done by this talent no longer receives modifications from effects that increase or decrease damage done by a percentage. The base weapon damage used in the calculation will still be modified by those effects.

Basically each time a crit happens it adds the dot calculation happens that includes present debuffs and buffs, any debuff that would increase or decrease the damage by a percentage added further shouldn't change the added crit growth
since deep wounds is a growing dot this means each time a crit gets added to the total growth that crit should account for the currently present debuffs/buffs that affect its percentage damage increase/decrease.

**Comment by UltraNix** [comment]
@Manpower99 Yep - you are right.
So no bug here.
