### ISSUE TITLE
[PALADIN] Hidden Strike Mechanics seem to be missing?

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1286]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Ret paladins have tons of 'hidden strikes' that are debuff applications, but are considered a melee hit in terms of procing effects, like Berserking, Judgement of Light, - WIsdom, Tiny Abomination in a Jar, Shadowmourne, even weapon skill gain.

Effects like this include:

Application of RIghteous Vengeace debuff 

Application of Vindication Debuff 

Application of Seal of Vengeance / Corruption Debuff.

Seal dmg of Seal of Vengeance / Corruption

Seal dmg of Seal of Command - on each target

Divine Storm on each target - this should be fairly obvious

Hammer of the RIghteous on each target.

All these hits should count as *hit* thus interacting with effects that happen on hit.

In my testing the proc rate of TAIAJ, and Judgement of Light healing seems way too low, so some of these aren't handled correctly.

Since I can't add spells on the PTR (AFAIK) I can't tell for sure which one is wrong.

For instance:

Judgement of Light has 15 ppm - so using a 3.7 weapon speed as base we can calculate, that the chance to proc JoL healing on any hit is as follows:

60 / 15 = 4 -> this means a weapon with a speed of 4.0 would be 100 % proc chance on every hit

3.7 / 4 = 92.5 % -> this means on every single hit, be it Auto, Crusader, Divine Storm, Judgement, or any of the hidden strikes mentioned here - there should be a chance of 92.5 % of procing the heal from the judgement.

With it having no ICD, we should se instances where An Auto + Seal + Ability + Seal + Vindication + RIghteous Vengeance happen all at the same time all these effects should have a chance of 92.5 % to proc the healing from JoL, or anything else that uses PPM, or fix % chance to proc on melee attacks.

The proc rates seem way too low currently for everything.

**How to reproduce:**

**How it should work:**

**Database links:** https://www.wowhead.com/wotlk/spell=26016/vindication

https://www.wowhead.com/wotlk/spell=31801/seal-of-vengeance

https://www.wowhead.com/wotlk/spell=348704/seal-of-corruption

https://www.wowhead.com/wotlk/spell=53382/righteous-vengeance

https://www.wowhead.com/wotlk/spell=20375/seal-of-command

**Comment by UltraNix** [comment]
Tested with Tiny Abomination in a Jar.
RIghteous Vengeace:
![image](https://github.com/user-attachments/assets/38050742-fd23-402f-a9c8-0a977f01ed7c)
1st stack from Crusader Strike, 2nd from melee and 3rd from Righteous Vengeance - no bug here.

Vindication - I see it's a magic effect,. not melee.
```
ID - 67 Vindication (Rank 1)
=================================================
Description: Gives the Paladin's damaging melee attacks a chance to reduce the target's attack poewr by $s1 for $d.
ToolTip: Attack power reduced by $s1.
Category = 0, SpellIconID = 1822, activeIconID = 0, SpellVisual = (6839,0), SpellPriority = 0
Family SPELLFAMILY_PALADIN, flag [0] 0x00000000 [1] 0x00004000 [2] 0x00000000

SpellSchoolMask = 2 (SPELL_SCHOOL_MASK_HOLY)
DamageClass = 1 (SPELL_DAMAGE_CLASS_MAGIC)
PreventionType = 1 (SPELL_PREVENTION_TYPE_SILENCE)
```
No bug here.

Seal of Vengeance:
![image](https://github.com/user-attachments/assets/0408709a-b515-46e1-8afb-1c9e39374892)
In combat log you see only one stack, but in my aura bar there 2 stacks of it - one from melee and one from Seal. No bug here.

Seal of Corruption:
![image](https://github.com/user-attachments/assets/b6b0385d-1f17-40d6-a345-9abbb99cde6c)
As above - no bug here.


Seal of Vengeance/Corruption weapon damage at 5 stacks:
![image](https://github.com/user-attachments/assets/27777a1e-b49f-4418-aa65-d7b62ec19002)
You can see how I get from 4 to 7 stacks. 1st from melee, 2nd from Seal of Vengeance refreshing and 3rd from Seal of Vengeance weapon damage effect. No bug here.
The same goes for Seal of Corruption :
![image](https://github.com/user-attachments/assets/75d238c5-debe-49a1-980b-d889ccc4e34f)

Seal of Command:
![image](https://github.com/user-attachments/assets/7d9cbe60-f848-4e14-958a-180a94d3ee62)
1 melee attack and 3 attacks from Seal - you can see 4 stacks. No bug here.

Divine Storm:
![image](https://github.com/user-attachments/assets/d77535f8-a43b-4ecb-8371-4d63909b1c11)
3 hits mean 3 stacks - as on screenshot. No bug here.

Hammer of the RIghteous:
![image](https://github.com/user-attachments/assets/7dcca070-5097-4ff2-b8ac-791413926a74)
1 melee stack + 2 targets from mean 3 stacks - as you can see.

I tested all of these spells and all works okay.

Judgement of Light/Wisdom are kinda different, cause they work on taken proc flags - so you need to do initial damage in order to proc it.
