### ISSUE TITLE
[Naxx] Ascended 10 man Gluth melee hits

### ISSUE THREAD

**Issue by Inukk** [gamefreedomgit/Frostmourne#131]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Our guild did gluth ascended this week and our tanks were getting hit twice every 1.1s, don't know if it's intended to work this way but I was told from a GM to report it as a bug.

Last week we did ascended and the damage our main tank was receiving seemed normal. Unsure if something changed since then

![mspaint_NDW5udh4Qg](https://github.com/gamefreedomgit/Frostmourne/assets/101921457/6023b32a-7f85-43b3-b717-8fc79cbebd47)

**Comment by RadeghostWM** [comment]
The damage is increased, but it shouldn't doublehit I think?

**Comment by Manpower99** [comment]
> The damage is increased, but it shouldn't doublehit I think?

I will test it as soon as i can join an ascended raid. gluth along with saph/kt are bosses that do parry haste in naxxramas so there is a chance this is parry haste. i can track it and screenshot it as soon as i can.

**Comment by Inukk** [comment]
> gluth along with saph/kt are bosses that do parry haste in naxxramas so there is a chance this is parry haste.

Do you happen to have a source for which bosses do parry haste? I tried finding info on my own but I couldn't find anything reliable

**Comment by Manpower99** [comment]
> > gluth along with saph/kt are bosses that do parry haste in naxxramas so there is a chance this is parry haste.
> 
> Do you happen to have a source for which bosses do parry haste? I tried finding info on my own but I couldn't find anything reliable
Only through warmane as they added some with proof from warcraftlogs which is no longer available to be seen sadly
Bkader's Skada addon supports tracking it better then details
https://avengingwrathy.wordpress.com/2010/01/15/bosses-who-parry-haste/
Gluth Sapphiron Kelthuzad Vezax Lady Deathwhisper Sindragosa Halion Onyxia Icehowl are bosses that do parry haste on warmane 100%. 
I have not tested ascended yet on ptr but when i can ill screenshot every boss that currently does in whitemane.

**Comment by RadeghostWM** [comment]
> > > gluth along with saph/kt are bosses that do parry haste in naxxramas so there is a chance this is parry haste.
> > 
> > 
> > Do you happen to have a source for which bosses do parry haste? I tried finding info on my own but I couldn't find anything reliable
> 
> Only through warmane as they added some with proof from warcraftlogs which is no longer available to be seen sadly. Bkader's Skada addon supports tracking parry haste better then details. https://avengingwrathy.wordpress.com/2010/01/15/bosses-who-parry-haste/ Gluth Sapphiron Kelthuzad Vezax Lady Deathwhisper Sindragosa Halion Onyxia Icehowl are bosses that do parry haste on warmane 100% I have not tested ascended yet on ptr but when i can ill screenshot every boss that currently does in whitemane.

So looks like it's blizzlike then?

**Comment by Manpower99** [comment]
> > > > gluth along with saph/kt are bosses that do parry haste in naxxramas so there is a chance this is parry haste.
> > > 
> > > 
> > > Do you happen to have a source for which bosses do parry haste? I tried finding info on my own but I couldn't find anything reliable
> > 
> > 
> > Only through warmane as they added some with proof from warcraftlogs which is no longer available to be seen sadly. Bkader's Skada addon supports tracking parry haste better then details. https://avengingwrathy.wordpress.com/2010/01/15/bosses-who-parry-haste/ Gluth Sapphiron Kelthuzad Vezax Lady Deathwhisper Sindragosa Halion Onyxia Icehowl are bosses that do parry haste on warmane 100% I have not tested ascended yet on ptr but when i can ill screenshot every boss that currently does in whitemane.
> 
> So looks like it's blizzlike then?

Thing is, screenshot he has linked is from details which doesnt have a good parry haste tracker like Bkader's details. as soon as i do 10Man Ascended i will screenshot it to confirm if this is parry haste or thrash or a double hit bug.

**Comment by oomshroom** [comment]
Parry-haste cannot reduce attack time below 20% of original. It cannot result in two swings at the same time.

**Comment by Afgann** [comment]
https://us.forums.blizzard.com/en/wow/t/maexxna-and-sapphiron-double-attack-hidden-ability/946089

dunno if it should also work like this in wotlk

**Comment by Manpower99** [comment]
After today's 25man, yes he does parry haste. have not experienced double hits (aka thrash) but it is likely the case of what happened to your tanks.

**Comment by Manpower99** [comment]
> https://us.forums.blizzard.com/en/wow/t/maexxna-and-sapphiron-double-attack-hidden-ability/946089
> 
> dunno if it should also work like this in wotlk

Using wow classic's database i can determine whic hbosses mobs should thrash based on combatlogs. it is accurate with vanilla's BWL three drake bosses and others.
https://wowclassicdb.com/wotlk/spell/3391 
check caused by and those are the confirmed mobs that should have a chance on hit to proc on next hit two immidiate attacks
functioning similar to a windfury effect. only one mob in naxxramas and its a trashmob should have that effect
similarly i found this :
https://github.com/azerothcore/azerothcore-wotlk/issues/6118

**Comment by Afgann** [comment]
Then what about this
https://us.forums.blizzard.com/en/wow/t/bosses-attacking-multiple-times-in-a-single-game-tick/950010

**Comment by Manpower99** [comment]
> Then what about this https://us.forums.blizzard.com/en/wow/t/bosses-attacking-multiple-times-in-a-single-game-tick/950010
thats 2021 Classic
In vanilla and bc many bosses did have it, along with crushing blow and parry haste.
in wrath crushing blow is +4 lvls instead of 3
Parry haste is limited to few bosses and Thrash is not on the vast majority of wotlk bosses
this was made worse by server ticks of batching.

Prime example of bosses that have both thrash an parry haste are Nightbane and Prince fights in kKrazhan which were destroying non warrior tanks, it is also why parry haste is disabled in some VERY hard hitting bosses such as Brutallus and Patchwerk.
but again wotlk thrash attack by bosses didnt happen reasoning was DK tanks being added to the game, Blizzard had to reduce the sudden tank damage elements to allow non shield tanks to actually survive bosses.
At the start of wotlk classic it was also bugged and every boss had parry haste but it was fixed not long after.
https://github.com/JamminL/wotlk-classic-bugs/issues/464
 
Regardless the bosses that do parry haste on warmane t7 are doing the same on whitemane t7 and one could conclude that this isn't a bug.
i will dig as much as i can of wotlk bosses that have Thrash and will report here

**Comment by RadeghostWM** [comment]
parry haste is not boss doubleattack so you're confusing things a lot

**Comment by Manpower99** [comment]
> parry haste is not boss doubleattack so you're confusing things a lot, also: https://us.forums.blizzard.com/en/wow/t/bosses-attacking-multiple-times-in-a-single-game-tick/950010 as Afgann linked

Iam not claiming they are, never said so either so not really confusing things at all im just claiming that parry haste works perfectly on tier 7 bosses on whitemane and that thrash should not happen in wrath bosses afaik
and again i said that post is from before classic wotlk its from 2021 which is tbc and classic era servers
double attack is "thrash" and bosses in wrath do not seem to have it, the vast majority of bosses do not have parry haste either as these two mechanics were very problematic with the addition of an extra non shield tank aka Death Knight so blizzard reduced the sudden damage mechanics for tank damage taken balance with very few exceptions.
even on warcraftlogs as that has proper timeline of events you can check all the logs made on phase 1/phase2 of wotlk classic
this guy never took two hits from gluth in the same second
https://classic.warcraftlogs.com/reports/aPzvFKLfXQy9hGHb#fight=10&type=damage-taken&ability=1&source=12
and this guy as a blood dk didnt either 
https://classic.warcraftlogs.com/reports/Vk1QN9qzPf826x7H#fight=15&type=damage-taken&source=13&ability=1

**Comment by Afgann** [comment]
fixed
