### ISSUE TITLE
Standard mob leash applies in dungeons and raids

### ISSUE THREAD

**Issue by BalanCV** [gamefreedomgit/Frostmourne#1315]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Currently, the mob leashing system from the open world (hit to extend leash range) applies in dungeons and raids as well.
This should not be the case and creatures aggroed inside dungeons and raids should have infinite leash range by default and only deleash/deaggro in case a player sits in evade spot (or vanish, feign death, etc)

**How to reproduce:**
Pull some mobs from far away with a hunter and run without touching them

**How it should work:**
This is pretty bad for running dungeons and raids fast having a hunter pull mobs with minimal interraction after first md hits.

**Database links:**

**Comment by Manpower99** [comment]
Yup, tried to pull alot of mobs in zulfarrak and they all reset halfway through the dungeon.

**Comment by Riztazz** [comment]
There can be other cases where mobs evade in instance after they are cannot find path to target for a bit and this won't be changed, it is to prevent a bunch of exploits.

**Comment by sputnikk** [comment]
I have first noticed this in Halls of lightning. After that it happened once in naxx as well.
Its been almost 2 months since this report and I haven't been in HoL anymore and also didn't notice anything strange in naxx since.

Basically this bug seemed to happen when tank body pulls a lot of minions but doesn't attack them, or when hunter pulled with misdirect while the tank was running - indicating something similar to the "extend leash range" that should only happen outside.

**Comment by Manpower99** [comment]
> There can be other cases where mobs evade in instance after they are cannot find path to target for a bit and this won't be changed, it is to prevent a bunch of exploits.

Understandable but it is preventing a regular way of playing the game which is just chain pulling multiple packs, they just reset. we all assumed its an anti boosting measure but it is actually making alot of pulls undoable ( even in 80 instances )

**Comment by Riztazz** [comment]
Well i could disable this for non-bosses i guess :P @RadeghostWM how should i tweak the "Cant reach player" system in instances?

**Comment by sputnikk** [comment]
Keep in mind that there are legit cases where mobs should evade, basically when there is no path available due to player being in an unreachable spot for the mob to path, the so called "evade spots/safe spot".
There's a chance I haven't noticed this recently because of the improvements in mob pathing that happened during these 2 months (or just because I haven't been doing dungeons)
Idk how hard it is to differentiate between the two code-wise.

**Comment by RadeghostWM** [comment]
Yeah, that should be reworked for non-boss mobs and if there's something wrong, we can fix it by case-by-case basis if its reported. dungeons should be mega-pullable.

**Comment by Riztazz** [comment]
Fixed, will close once it's live
