### ISSUE TITLE
in arena people just stand with back in the wall and i cant ambush or backstab

### ISSUE THREAD

**Issue by Roswald1334** [gamefreedomgit/Frostmourne#1324]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
in 2v2 arena, the ones i face just backpeddle into the wall with their backs so it is impossible to reach their backs. on other private servers there is always a hologram wall a inch from the actual wall so that you can still get in backstabs and ambushes when standing ontop of the other players

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by UltraNix** [comment]
Private servers are not any reference for us.
Show us some video from retail that it's a bug.

**Comment by roperoperope** [comment]
i havent seen this on warmane, this hologram wall u speak of, i used to play feral rog 2s and it sucked

**Comment by haephaistoss** [comment]
It isn't a bug, it's a well known tactic, you can't be behind the target if he's in the wall - since you can't enter the wall...

Also in Dalaran Arena you should be able to stand on the edge exactly, and if rogue shadowsteps, or druid feral charge - cats on you they should instantly fall down and not be able to hit you, a trick as old as time

**Comment by WhitemaneIsa** [comment]
No further infos/complaints, closing.
