### ISSUE TITLE
Mage Frost Nova issues

### ISSUE THREAD

**Issue by qwerty4444444444444444444444444** [gamefreedomgit/Frostmourne#133]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (wotlk-twinhead.twinstar.cz)

**Description:**
Spell feels weird and clunky. So far I've realised problem of mobs not being snared even tho they are in range and there is no resist or miss.
And one more thing which happens almost all the time. If you line of sight mob around some object smaller size that they need to go around in order to get to you, if you Frost Nova they wont get snared.

**How to reproduce:**
Kite a mob around smaller object and try to snare them with Frost Nova in your range.

**How it should work:**
They should get snared
**Database links:**

**Comment by Inukk** [comment]
> So far I've realised problem of mobs not being snared even tho they are in range and there is no resist or miss.
Have you checked if this specifically happens during movement? it might be related to the leeway fix they implemented recently, dpsing the floating adds on malygos phase 2 has also felt super janky ever since the leeway fix

**Comment by Manpower99** [comment]
> > So far I've realised problem of mobs not being snared even tho they are in range and there is no resist or miss. <
> 
> Have you checked if this specifically happens during movement? it might be related to the leeway fix they implemented recently, dpsing the floating adds on malygos phase 2 has also felt super janky ever since the leeway fix

i dont think leeway is added yet.

**Comment by Manpower99** [comment]
> **Description:** Spell feels weird and clunky. So far I've realised problem of mobs not being snared even tho they are in range and there is no resist or miss. And one more thing which happens almost all the time. If you line of sight mob around some object smaller size that they need to go around in order to get to you, if you Frost Nova they wont get snared.
> 
> **How to reproduce:** Kite a mob around smaller object and try to snare them with Frost Nova in your range.
> 
> **How it should work:** They should get snared **Database links:**

I don't think this is at all related to leeway since its not added yet, leeway is also a beneficial thing that usually improves and increases the radius and ranges to accomodate for higher ms.

However i do think this is a trinitycore issue in general of several abilities that function off the character's center, such as frost nova, holy nova an arcane explosion and possibly others too like piercing howl/demoralizing shout and roar.

https://github.com/TrinityCore/TrinityCore/issues/3923 
This is a bug report that existed since 2011 and is still not fixed. from what i tested on another stock trinity core server it is still an issue, it is also an issue on trinity core 4.3.4.

To be specific on what the bug is based on this report : all AOE spells with area centered to caster (for example Arcane Explosion) have a reduced radius, for example they have 8.5 yard radius instead of 10 yard. In general the radius of those spells is reduced of 1.5 yard.

This was an issue on previous Sunwell.pl servers as well : https://github.com/SunwellTracker/issues/issues/2544

**Comment by Inukk** [comment]
> i dont think leeway is added yet.

You're right, it was only implemented for hunter traps, I misread

**Comment by Afgann** [comment]
fixed
