### ISSUE TITLE
Conflagrate is bugged (Warlock Destruction's Ability)

### ISSUE THREAD

**Issue by Naturlish** [gamefreedomgit/Frostmourne#135]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
![Screenshot 2024-02-11 092352](https://github.com/gamefreedomgit/Frostmourne/assets/54108446/a5134053-5b01-4b66-85ba-1365d8f4e221)

[//]: # (http://wowhead.com/)
https://www.wowhead.com/wotlk/spell=17962/conflagrate

[//]: # (wotlk-twinhead.twinstar.cz)
https://wotlk-twinhead.twinstar.cz/?spell=17962

**Description:**
Conflagrate is delayed by 1 second whenever an immolate effect is applied on the target.

**How to reproduce:**
When you cast immolate on a target, conflagrate will trigger immediately.

**How it should work:**
It should be instant, and not delayed by 1 second.

**Database links:**
https://wotlk.evowow.com/?spell=17962

PS: It doesn't make any sense for conflagrate to trigger 1 second after an application of immolate on the target. Otherwise it is impossible to instant cast conflagrate on a dispeller with a fast reaction. Please fix it!

**Comment by Inukk** [comment]
This is intended and I believe it's behaved like that since vanilla, this has already been reported in the past on azerothcore, sunwell and chromiecraft, and the general consensus is that it's blizzlike

https://github.com/azerothcore/azerothcore-wotlk/issues/3458
https://github.com/SunwellTracker/issues/issues/1254
https://github.com/chromiecraft/chromiecraft/issues/1136

I found a video from 2010 that claims it's 3.3.5 ptr, and you can see the delay in action at the 2:37 mark
https://youtu.be/QUBG36nDQ0g?si=9l1eO7bVrwN2r5Wo&t=154

**Comment by Naturlish** [comment]
Very strange then.

This is a screenshot from Wotlk Classic just now, and it proves the opposite fact.

Anyway, I am assuming Wotlk Classic Activision/Blizzard isn't just Blizzard anymore...

![image](https://github.com/gamefreedomgit/Frostmourne/assets/54108446/4b43b2bd-de92-474b-a1ce-9e763635b40b)

**Comment by Inukk** [comment]
Might have been a classic class change then, if that's the case I'd support adding this as a suggestion to remove the 1s delay

**Comment by Naturlish** [comment]
This would be great! Anyone (especially Whitemane staff) can check by themselves on Classic if they want confirmation.

**Comment by scrublama** [comment]
Always was like this on 3.3.5

**Comment by tankpajzl** [comment]
it should have delay for example-[https://www.youtube.com/watch?v=nhy2lYG8rto&t=32s](url)
