### ISSUE TITLE
[NPC] Galak Messenger

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#139]
Mob either does not exist, or the patrol path it is using is very inaccurate.

EDIT: Never mind it does exist, however there is a bug where he stops his patrol path completely when a player is not in visible range of him.

**Comment by qqdbpp** [comment]
found him on normal patrol route. maybe he has some weird spawn condition 
![image](https://github.com/gamefreedomgit/Frostmourne/assets/159703358/50414a0a-de11-4898-9ae2-87e7d55a005f)

**Comment by qqdbpp** [comment]
btw mobs on this server dont do anything unless they are rendered by some player, so you cant wait for him to patrol past you. you have to spawn him yourself. if you wait for him to run out of render distance he just freezes there

**Comment by Godmatik** [comment]
OK well that is the bug then, the mob should be spawned and rendered on their own without needing someone to be present

**Comment by Godmatik** [comment]
I've walked his patrol path that is precisely shown on wowhead several times in both directions - still unable to render/see/spawn him

**Comment by Godmatik** [comment]
Found the issue - the patrol path he is using is definitely not the one on WoWhead, he follows the road further south, so this needs to be updated

**Comment by Afgann** [comment]
fixed

**Comment by qqdbpp** [comment]
> fixed

please reopen since this bug affects every mob that has a patrol path, not just galak messenger. i have tested and confirmed it for ghost howl, luzran , knucklerot, shadumbra, ursangous and blackmoss the fetid. maybe you could fix all at once by having mobs not rely on players rendering them to do their stuff (or seperate mobs into 'wander' and 'patrol' types?)
