### ISSUE TITLE
Demonic Pact Tooltip

### ISSUE THREAD

**Issue by OGWako** [gamefreedomgit/Frostmourne#1438]
**Description:**
Demonic Pact Tooltip should show spell power gained from buff within tooltip

**How to reproduce:**
Gain Demonic Pact

**How it should work:**
Demonic Pact Tooltip should show spell power gained from buff within tooltip
![image](https://github.com/user-attachments/assets/3bf60221-afcb-4013-b604-10a8f0167ae2)
Like this

**Comment by disruption01** [comment]
I believe thats a WOTLK classic addition

**Comment by Manpower99** [comment]
Thats a change in wotlk classic, since the base client they used was from the legion expansion which allowed for dynamic buff tooltips changing their values on a small timer.
you can notice it also in the buff from power word shield, it does not update its tooltip in this client but it does update its tooltip in the classic client. which is why the shield absorb in wotlk client is purely based on estimation (which is exactly why theyre never accurate on any healing/absorb meter, the most accurate one being RevisitedSkada by Bkader), however in wotlk classic due to the tooltips being updated the estimation is no longer necessary which is why Classic's healing/absorb meters are  very precise when it comes to this.
The client we play on does not have that feature, the only solution to it is when private server emulation starts adopting the 3.4 client.

**Comment by OGWako** [comment]
Oh that makes a lot of sense,
Sad that certain QoLs are limited by client versions and backport capability.

**Comment by Manpower99** [comment]
> Oh that makes a lot of sense, Sad that certain QoLs are limited by client versions and backport capability.

Indeed it is, even for weak auras  and the modern weak aura addon having more functions and less limitations.
there is alot of talk from Gaga in the whitemane discord that they're planning on implementing a 3.4 Client in the future so maybe we get something eventually.

**Comment by OGWako** [comment]
Appreciate the insight <3
