### ISSUE TITLE
Weapon Enchant Crusader - Probably the wrong proc chance value is set.

### ISSUE THREAD

**Issue by InterstellarWhitemane** [gamefreedomgit/Frostmourne#1445]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Weapon Enchant Crusader not working. From lvl 2 i exping with Bloodied Arcanite Reaper with crusader ench. I have only 1x proc of this ench for 9lvls (from lvl 2 to 11) - from 157 melee hits + 33 judgements. Thats under 0.66% proc chance. Probably the wrong proc chance value is set.

**How to reproduce:**

Log in game, apply ench on weapon and kills the mobs.

**How it should work:**

This enchant is meant to be a frequent proc. +- 9% with my heirloom two hand axe.

**Database links:**

https://www.wowhead.com/classic/spell=20034/enchant-weapon-crusader

**Comment by Manpower99** [comment]
Wow classic had 1PPM on crusader enchant, it definitely looks like its lower on live relm
worth to note though it should diminish at the rate of 4% per level over 60, regardless of the actual tooltip.
So at 70 it would give 60STR instead of 100
at 80 it would give 20STR
The diminishing part works on whitemane which means if the PPM gets fixed should work accurately.

**Comment by Godmatik** [comment]
Confirmed, its set way too low

**Comment by UltraNix** [comment]
It is 1 PPM - with 2.9 speed weapon it will be ~5% chance.

**Comment by Manpower99** [comment]
so was PPM being calculated incorrectly on every enchant or what exactly

**Comment by haephaistoss** [comment]
just be thankful and hope it'll be OK now <3

**Comment by UltraNix** [comment]
There is no bug here - PPM is okay.
But there were a slight bug with rounding the proc chance.
