### ISSUE TITLE
Mage Molten Armor crit calculation probably wrong

### ISSUE THREAD

**Issue by andjsavin** [gamefreedomgit/Frostmourne#1505]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

When I equip neck without spirit (screenshot added) I have more crit than with neck with spirit (screenshot added).
![image](https://github.com/user-attachments/assets/0fae41d3-8b80-4397-af1f-12590edf867c)
![image](https://github.com/user-attachments/assets/10a65631-a4f3-448c-82fc-a8fa12c2aeec)
My meta gem works in both situations. 
![image](https://github.com/user-attachments/assets/27019b55-4e17-492a-ac62-53dca4d08953)
![image](https://github.com/user-attachments/assets/e19780b9-fae0-44c9-a666-9baf4f412074)

I'm not sure where the bug is, but I should have slightly more crit with spirit neck. Maybe some bug in Molten Armor formula or Glyph of Molten Armor?

**How to reproduce:**
Item with spirit gives less crit than item without spirit.

**How it should work:**
Item with spirit should give more crit.

**Database links:**

**Comment by haephaistoss** [comment]
In my testing on PTR it seems to be OK, for some reason.

561 spirit * 0.55 = 308.55 -> this gets rounded up to 308, because server just cuts numbers :D

And 308 crit rating is added to my mage, exactly as it should

You should try with items one by one, and see what causes the issue, or ask a gm to remove all auras from you maybe?
