### ISSUE TITLE
WARLOCK LIFE TAP ISSUE. 

### ISSUE THREAD

**Issue by OmarEZR** [gamefreedomgit/Frostmourne#1533]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When you Life Tap yourself, your trinket, lightweave embroidery tailoring cape, trinkets etc, should PROC, but they do not, only if you use "Health Funnel" it works, but on real classic, it LIFE TAP does proc everything, including trinket and stacks of the ILLU trinket too. 

**How to reproduce:**

**How it should work:**
Make sure that Life Tap lets proc all ur trinkets, cape, etc etc plz. 

**Database links:**

**Comment by Gruonden** [comment]
Why would you want that? xD Its a shitty mechanic. Its really not convenient to swap your trinket to life tap before pull, you definitetly didnt play warlock xd

**Comment by UltraNix** [comment]
@OmarEZR Please, provide some retail (aka 3.3.5) sources it's a bug.

**Comment by Eradicatepls** [comment]
Life tap should only allow Illustration or Muradin Spyglass to stack and that's all, shouldn't proc tailoring or any proc based trinket such as Dying curse.

**Comment by Steadydnt** [comment]
Yes i agree it should stack up trinkets like Muradins or Illu but it should not proc dying curse or lightweave embroidery. With "Real Classic" what do you mean? Blizzards Wotlk Classic?? There it wasnt proccing lightweave or dying curse aswell. If you mean other private servers with real classic yea you might be right. On Warmane Dying Curse procced from accepting a readycheck , or aswell from Eating Fish or either from using a pot. If you want that shitty kind of Interaction pls go there :D

**Comment by Rowern96** [comment]
@UltraNix @Eradicatepls @Steadydnt i looked for videos of wrath form back in the days of warlocks playing with illu and i found https://youtu.be/Fh3IukAHiHU?si=_Ql6-UEyEYMb6F2m&t=63 where at 1:03 with the refresh of the life tap glyph (is tracked in the middle of the screen) the illu duration at 10 stacks is refreshed -> life tap triggered illu. 
not sure if it from 3.3.5 thos since its in ulduar, but also not sure how many videos are there where wl still uses illu in 3.3.5.
also if it worked while it was a relevant trinket and got only changed after (maybe as a result of another change) was it intended not to work?

**Comment by Piootrek** [comment]
That should be already fixed. Closing.
