### ISSUE TITLE
Lock Summon: Infernal doing less damage then intended

### ISSUE THREAD

**Issue by Gruonden** [gamefreedomgit/Frostmourne#1550]
**Description:**

Hey, I noticed that "Summon Infernal" is significantly underperforming in terms of melee damage. I ran some tests and found that its melee attacks only average around 650-700 damage per hit. In comparison, on Classic WotLK and other WotLK private servers, each melee hit deals approximately 2000 damage. This bug makes the 10-minute cooldown almost useless since that barely deals 10k more damage than your regular pet. 

**How to reproduce:**
Cast Summon: Infernal and look on Details, Skada etc. 

**How it should work:**

Probably base damage or scaling should be fixed. 

**Database links:**

Phase 1 (Naxxramas)
https://classic.warcraftlogs.com/reports/g9h1zLyAtDjf7rX4#fight=20&type=damage-done&source=6

Phase 6 (Icecrown Citadel)
https://classic.warcraftlogs.com/reports/LCrRxGafHd8tVng1#fight=1&type=damage-done&source=37

**Comment by Eradicatepls** [comment]
Yes infernal is arguably not even worth the gcd atm. It might even be better not to even cast it i don't know exact maths, but yeah

**Comment by BalanCV** [comment]
https://github.com/wowsims/wotlk/blob/master/sim/warlock/inferno.go
@UltraNix i know you were looking into this in previous post.
BaseDamageMin:  330,
BaseDamageMax:  494.9
infernal.AutoAttacks.MHConfig().DamageMultiplier *= 3.2

I honestly have no idea where this 3.2 multiplier to melee swings comes from, but multiplying the base attacks with this seems to accurately reflect the melee damage done by infernal in classic(after standard target armor). Not sure if you want to do the same thing, but hope this info helps.

**Comment by PanJanuszek** [comment]
Pure damage on 80 lvl is (**1182**  - **1537**) on 0 armor target.
If you add [%] armor reduction, you will have your numbers. Can you test it?

**Comment by Steadydnt** [comment]
I also had a threat open of this like 1 month ago. There were 2 quiet nice calculations sent with prove etc.
Its just doing less then 50% with Melee attacks. It feels so bad as an Affliction to only have 1 cooldown in their whole Kit and this Cooldown is doing -50% dmg then it should do. While other classes get Custom Legendaries or small buffs. This was my post: https://github.com/gamefreedomgit/Frostmourne/issues/1299 it provides different calculations and prove that its working very badly here.

**Comment by Steadydnt** [comment]
I also found out now its 100% Base dmg that should be fixed. It doesnt scale at all or only a very very little with spellpower. You can compare from Warcraftlogs Wotlk Section that there is no huge difference between a Phase 1 Infernal and a Phase 4 Infernal in ICC. Pls check all for yourself there is something really wrong with the Base dmg here on Whitemane.
This is Phase 1 KT Naxxramas (Average 217 Itemlevel). Check all the Warlocks for yourself how much they are doing with Summon Infernal:
https://classic.warcraftlogs.com/zone/rankings/1015#boss=101114&partition=1&class=Warlock&spec=Affliction

To compare here is Phase 4 Icecrown Citadel Deathbringer Saurfang (Average 275 Itemlevel):
https://classic.warcraftlogs.com/zone/rankings/1020#boss=848&partition=4&class=Warlock&spec=Affliction

(Basically Infernal doing same damage even with +1300 Spellpower Phase 1 bis vs Phase 4 bis gear)

**Comment by Rowern96** [comment]
u can find alot of imformation from using a macro ingame while infermal is active:
/dump UnitAttackPower("pet")
/dump UnitAttackSpeed("pet")
/dump UnitStat("pet",1)
/dump UnitStat("pet",2)
/dump UnitStat("pet",3)
/dump UnitStat("pet",4)
/dump UnitStat("pet",5)
/dump GetPetSpellBonusDamage()
/dump UnitClass("pet")
/dump UnitDamage("pet")

![image](https://github.com/user-attachments/assets/83d73c79-b3e3-4525-8296-7752f2d88928)

this was done before the attack speed  fix tho and might be some old data also got this one with deathchill equipped and with unit damage:

![image](https://github.com/user-attachments/assets/e8ea2cfe-2769-4290-93a6-b1f6d0871916)

the right one with atack speed fixed has no equipment at all.

	infernal := &InfernalPet{
		Pet: core.NewPet("Infernal", &warlock.Character, stats.Stats{
			stats.Strength:  331,
			stats.Agility:   113,
			stats.Stamina:   361,
			stats.Intellect: 65,
			stats.Spirit:    109,
			stats.Mana:      0,
			stats.MeleeCrit: 3.192 * core.CritRatingPerCritChance,
		}, statInheritance, false, false),
		owner: warlock,
	}
this is the base stats from wowsims, and they match the once from warmane alot more (the different stamina might be because of the pets stamina scaling, so 361 is base but it gets increased by a % of the wl (not sure what scales from inferno and what doesnt)
as u can see there is a big difference in the base strength and the atack power scales with 2*strength, which would explain the different base atack power values between warmane and whitemane (infernal base attack power is 2*strength -20 for both, same as in wowsims)
sadly we cant test on wrath classic and i am not sure if infernal on warmane does same amount of damage as on classic or what it was like in original wrath, but fixing the base stats would prob be a good start and maybe check the base stats of characters at the same time https://github.com/gamefreedomgit/Frostmourne/issues/1277

also take into consideration just going with classic infromation about infernal (or rawr/wowsims) since its already hard finding  information about it and retail wrath is now 15 years old.

if we should test specific things and report back let us know, otherwise its hard to know what to look for
