### ISSUE TITLE
[Quest] Quest Polishing The Helm (13006) is not rewarding XP

### ISSUE THREAD

**Issue by WhitemaneChronus** [gamefreedomgit/Frostmourne#1559]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**

Daily quest (13006) is not rewarding xp upon turning in.
Even though in game this id shows "Polishing the Helm" on wowhead its [A Viscous Cleaning
](https://www.wowhead.com/wotlk/quest=13006/a-viscous-cleaning)
maybe that has something to do with it.
here's a photo submitted by the player as well (chat settings include experience)

![uIeBZzc](https://github.com/user-attachments/assets/9ffe4af8-9e84-4173-b959-28f998904315)

**How to reproduce:**

Take quest 13006, complete it and turn in.

**How it should work:**

Should reward experience.

**Database links:**

**Comment by PanJanuszek** [comment]
About name:

"Unlike the Black Temple or Karazhan, the all-male faction of Ice isn't being made more diverse by replacing the quartermaster with a female or being renamed to the Sons and Daughters of Hodir, but many of the quests that players may remember grinding day in and out to unlock exalted [shoulder enchants](https://www.wowhead.com/item=50335) have been renamed to avoid various sexual innuendos. Turns out, the Sons of Hodir have a pretty bawdy sense of humor!
"

This quest has old title, that's all

**Comment by WhitemaneChronus** [comment]
@PanJanuszek 
Here´s another case of player not getting experience rewards from sons of hodir quests.
Both of these players have been hardcore, first (in original post) spanish client, this report is for english client:

This links shows the quests + rewards:
https://imgur.com/a/fCUVRYM
same player, same client, same time turned in another normal quest:
https://imgur.com/a/Po13YOe
