### ISSUE TITLE
Spell queue is not 400ms

### ISSUE THREAD

**Issue by Robosterone** [gamefreedomgit/Frostmourne#156]
**Description:**
Default spell queue should be 400ms, it is barely 50ms now.

**How to reproduce:**
Press another cast 0.1 or 0.2 or 0.3 seconds before your current spellcast is over and nothing will happen. You'll get your spell queued only at the very very end of the cast, my guess is 0.05s.

**How it should work:**
Should be 400ms default. I've also found out they have spellque active only for casts, not gcds on warmane. However in retail/classic there is also spellque for GCDs.

**Database links:**
http://thedefiantguild.com/forums/discussion/15431.html

**Comment by Manpower99** [comment]
Very noticable it is around 40ms currently which is imo not enough. u have to queue the spell at the exact end of the cast for it to trigger which is not adding much.

**Comment by Robosterone** [comment]
https://us.forums.blizzard.com/en/wow/t/what-exactly-is-spell-batching/479550/5
http://thedefiantguild.com/forums/discussion/15431.html

**Comment by BalanCV** [comment]
^This
400ms of spell queue window is simply having the mechanism of telling the server which spell you want to cast next 0.4sec before your next cast, negating a lot of effects of personal lag for casters and stopping the need to button mash. 400 ms is the default spellqueue window in blizzard.

Batching on the other hand is a complex division of server action processing into "batches" of time. In this case having all actions that happened within 0.4sec happen at once will definitely create a feeling of server lag and maybe even issues. 400 ms batching was what they had in vanilla ( a very slow and laggy feeling game by design)
In wrath you don't need or WANT that much, its a fast paced game compared to the past 50ms max i'd say (which is what i suspect current implementation has around)

**Comment by Robosterone** [comment]
Good explanation, so I guess it would be ideal to reduce batching as low as possible or even disabling it and adding a queing system.

**Comment by BalanCV** [comment]
I definitely wouldn't say disable it. Both of these are, in a way, methods of lag prevention and have very good uses. Ofc there are people I've seen advocate both for and counter.

Here is a github post for official wow classic that is very well put and comes from an established pvp player. I think he offers a very good argument for batching and even gives out a number he feels is good (1-150ms)

https://github.com/JamminL/wotlk-classic-bugs/issues/120
https://www.youtube.com/watch?v=m6P-fHQ-guI

Very good read and watch if interested in the subject.

**Comment by Afgann** [comment]
fixed
