### ISSUE TITLE
[PTR - Ulduar25m] Freya 3 elders, unstable energy and ground tremor trimers are incorrect

### ISSUE THREAD

**Issue by gforghieri** [gamefreedomgit/Frostmourne#1587]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

[PTR - Ulduar25m] Freya 3 elders, unstable energy and ground tremor trimers are incorrect

Unstable energy should occur every 30s

Ground tremor should occur every 30s

Source wowhead: https://www.wowhead.com/wotlk/guide/raids/ulduar/freya-strategy

![image](https://github.com/user-attachments/assets/e0f281ac-1f78-42cb-be78-1d08f22b5818)

**Comment by Manpower99** [comment]
Yes i was going to make a bug report on this but since you did i'll just comment here :
Roots cooldown should be on 30s, this is essentially in order with some other HM spells including Ground Tremor and Unstable Energy. https://www.youtube.com/watch?v=LhZUqQy1pcc&t=309s see his dbm (and also the roots themselves) appearing every 30s
 All three abilities should run on a separate, roughly half minute cooldown, otherwise Freya would use them in a random order.

**Comment by NickZedd** [comment]
@Afgann 
This was applied in a way where the roots and beams now happen exactly every 30 seconds, and will always happen at the exact same moment. Tested in 25 nm hardmode.

Manpower99 mentioned how they have roughly the same cooldown, otherwise she would use them in a random order. This might technically be true, but the random variance of these abilities is so large that the order is random anyway. 

The first thing I see when clicking the linked video is the ground tremor being delayed by about 35 seconds (his timer is on 24 sec). I recently had a look at other videos as well and the roots sometimes happen more than one minute apart, but it's extremely random. They also seem to happen faster in p2. In a different video the roots once happened 12 seconds apart (can't find it).

This huge variance is not enjoyable in my opinion, and should not be emulated. There should be some variance, so that the abilities don't always line up in the exact same way which would make the fight stale and boring, but not knowing if  an ability will happen in 1 second or in 30 seconds is just annoying imo.

In this video at this timestamp you can see that she does sometimes cast tremor faster (after 23 sec just like the timer), so the cooldown is not actually 30 seconds but she usually casts it after 30-40 from what I've seen.
https://www.youtube.com/watch?v=AQwSRE6JBgw&t=384s

https://www.youtube.com/watch?v=wyYZq6jHNq8
0:30 roots
1:34 roots
2:32 roots
3:34 roots
4:03 roots
4:34 roots
5:34 roots
6:06 roots
6:43 roots
7:27 roots
7:47 roots
8:08 roots
8:31 roots
8:53 roots
9:08 roots

**Comment by Manpower99** [comment]
> @Afgann This was applied in a way where the roots and unstable energy now happen exactly every 30 seconds (after the 1st set), and will always happen at the exact same moment. Ground tremor is also happening exactly every 30 seconds, but not at the same time as beams and roots. Tested in 25 nm hardmode.
> 
> Manpower99 mentioned how they have roughly the same cooldown, otherwise she would use them in a random order. This might technically be true, but the random variance of these abilities is so large that the order is random anyway.
> 
> The first thing I see when clicking the linked video is the ground tremor being delayed by about 40 seconds (his timer is on 23 sec). I recently had a look at other videos as well and the roots sometimes happen more than one minute apart, but it's extremely random. They also seem to happen faster in p2. In a different video the roots once happened 12 seconds apart (can't find it).
> 
> **This huge variance is not enjoyable in my opinion, and should not be emulated**. There should be some variance, so that the abilities don't always line up in the exact same way which would make the fight stale and boring, but not knowing if an ability will happen in 1 second or in 30 seconds is just annoying imo.
> 
> In this video at this timestamp you can see that she does sometimes cast tremor faster (after 23 sec just like the timer), so the cooldown is not actually 30 seconds but she usually casts it after 30-40 from what I've seen. https://www.youtube.com/watch?v=AQwSRE6JBgw&t=384s
> 
> https://www.youtube.com/watch?v=wyYZq6jHNq8 0:30 roots 1:34 roots 2:32 roots 3:34 roots 4:03 roots 4:34 roots 5:34 roots 6:06 roots 6:43 roots 7:27 roots 7:47 roots 8:08 roots 8:31 roots 8:53 roots 9:08 roots

nickzed is correct, the three hardmode abilities iron roots, ground tremor and unstable energy should be on a 30second cooldown. it doesn't necessarily mean all three should happen 30seconds at the same time. infact you can notice that they seem to have some sort of an 8second category cooldown also ( if one of them happens, the other one gets roughly 8 extra seconds added to the cooldown so they dont overlap ). @Afgann

**Comment by Afgann** [comment]
fixed
