### ISSUE TITLE
Vanish Bug

### ISSUE THREAD

**Issue by benhebba** [gamefreedomgit/Frostmourne#1646]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Hey
a little problème with vanish.
Vanish is Removing the (Debuff) on the target For Example : Deadly poison or Rupture
like As soon as u press Vanish whatever Debuff u have on the target (rupture or deadly poison) it's instant Removed.

**How to reproduce:**

**How it should work:**
Vanish shouldn't be removing Any debuff from the Target

**Database links:**
Example how Vanish should work "at 1:20" https://www.youtube.com/watch?v=JebYx87eTqQ

**Comment by Riztazz** [comment]
The linked video is past boss death and nothing happens there

**Comment by Riztazz** [comment]
I cannot reproduce this in either PVP nor PVE, the only case i can see it happen when you fight the creature alone and it evades right away which is correct behavior.
How can i reproduce this?

**Comment by benhebba** [comment]
Yes correct but still even if ur fighting The dummy Alone shouldn't be removing the Debuffs when u vanish at some point it's bugging for me 40% of the time ,for Example sometimes when ur fighting The boss and u vanish it's removed the debuff sometimes not ,i guess it's because of the reason that ur lossing the debuff when ur fighting the dummy i'm saying is not all the time on boss but it's happening sometimes .

**Comment by Riztazz** [comment]
It's a normal mechanic, you fight, you evade the creature, the creature goes back home. In case of dummies home is where they stood. But i'll adjust how dummies in particular evade (only dummies) because they've been bothering me for a while during tests.

I cannot reproduce the case where bosses lose my debuffs when i vanish, i've tried to reproduce it in many ways and the dots are always there as long as boss is in combat, especially raid bosses.
Any chance i could get a video of it happening?
