### ISSUE TITLE
[Warlock] Shadow Embrace bug

### ISSUE THREAD

**Issue by Covidisreal** [gamefreedomgit/Frostmourne#1666]
Today, during boss fight with Heigan, my shadow embrace stacks randomly stopped getting refreshed / applied from both shadow bolt and haunt. This happened to me for the first time, and i honestly can't provide any further information to help investigating. :(

**Comment by haephaistoss** [comment]
Are you the only one with the talent?
Sometimes on other servers it happened that since it isn't stacking anything further than 1 application, if another warlock had it applied yours could be forgotten and vice versa - but the dmg output did not change.

Did you notice your numbers getting off too or was it only visual?

**Comment by Riztazz** [comment]
This is not the case on this server, each warlock should have their own version of the debuff
What i'm suspecting currently is clients aura count limit, only N buffs/debuffs can be displayed by unitframes. I've seen similar reports like:
https://github.com/gamefreedomgit/Frostmourne/issues/1424

@UltraNix @Piootrek  Tagging because i am kinda lost with both of these issues, i've tried multitide of things and simply cannot reproduce

**Comment by Covidisreal** [comment]
@haephaistoss No, had 2 more afflis in raid, and no, i don't track dmg done in real time via combat text or something similar so can't tell. 

@Riztazz I don't think it's a "displayed aura limit on unitframes" type problem. Firstly, i have more than enough max auras displayed on target enabled to track all my debuffs and even more, secondly - I saw it expiring on target while i kept casting sbolts, and it just wasn't getting refreshed so it fell off completely and i couldn't apply a single stack back on boss until the end of the fight.

**Comment by Riztazz** [comment]
#1610 is unrelated, i'm gonna try and debug this one now

**Comment by Riztazz** [comment]
I have a few more questions:
did you die during the encounter and got resurrected?
if you did not die on the boss, did it fix itself on next boss?
did you relog in between?

Next time it happens please take a few screenshots, i'm unable to replicate this

**Comment by Riztazz** [comment]
fixed, will close once it's live
