### ISSUE TITLE
Corruption - snapshot

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Frostmourne#1696]
**Description:**
Corruption currently is snapshoting some stats(haste and SP) when its timer is refreshed by casting shadow bolt/haunt/drain soul.

**How to reproduce:**
Put corruption with snapshotted stats and start casting shadowbolts.

**How it should work:**
Everlasting Affliction doesn’t only refreshes  Corruption through  Drain Soul,  Shadow Bolt and  Haunt. It also introduces a niche mechanic where certain calculations that affect the damage that  Corruption deals do not get updated when refreshed through [ Everlasting Affliction](https://www.wowhead.com/wotlk/spell=47205/everlasting-affliction) but stay the same as on the application. If we want to update these modifiers you got to manually reapply [ Corruption](https://www.wowhead.com/wotlk/spell=47813/corruption) by casting it again. This has big implications for what we want to do prior to applying our  Corruption so that we can get an as strong as possible version for as long as possible. Making certain cooldowns or buffs last way longer for [ Corruption](https://www.wowhead.com/wotlk/spell=47813/corruption) than they normally do. We call these modifiers that “rollover”

**Database links:**
https://www.wowhead.com/wotlk/guide/classes/warlock/affliction/dps-rotation-cooldowns-abilities-pve#standard-rotation

**Comment by crabcakeowo** [comment]
What is this change? Corruption was working fine with everlasting affliction.

**Comment by Scolix9** [comment]
What was the problem? Because in your ticket you didn't specify how it is working. Because haste + SP are supposed to work dynamically but you didn't write that either.

**Comment by Steadydnt** [comment]
I dont get it either what is supposed to be changed? 
When you talked about rollover do you mean that for example on Thaddius dmg% Polarity / Loatheb 50%crit Spore / Ironcouncil 50%dmg Rune of Power etc. you did not have to re-apply corruption because Haunt/SB/DS would apply these % buffs already? 
If this was the fix then its correct.

**Comment by Manpower99** [comment]
i dont get it either, what actually changed? @Afgann

**Comment by Sketish** [comment]
Dmg and haste of corruption wont change unless you manually press it. Shadow bolt just reset duration.

**Comment by Sketish** [comment]
> I dont get it either what is supposed to be changed? When you talked about rollover do you mean that for example on Thaddius dmg% Polarity / Loatheb 50%crit Spore / Ironcouncil 50%dmg Rune of Power etc. you did not have to re-apply corruption because Haunt/SB/DS would apply these % buffs already? If this was the fix then its correct.

fake warmane info. Read how it worked on old wotlk/classic wotlk.

**Comment by Scolix9** [comment]
> Dmg and haste of corruption wont change unless you manually press it. Shadow bolt just reset duration.

Do you know how everlasting should work or just writting things with zero to no evidence? Every time you have haste + SP procs (or even crit dmg) it gets applied on ur corruption for the amount of time you have the buffs. Your statement has zero evidence. You only stated how the talent works through wowhead. 

Wotlk Classic had the exact same "feature", but most likely you didnt even test it there .

**Comment by Sketish** [comment]
> > Dmg and haste of corruption wont change unless you manually press it. Shadow bolt just reset duration.
> 
> Do you know how everlasting should work or just writting things with zero to no evidence? Every time you have haste + SP procs (or even crit dmg) it gets applied on ur corruption for the amount of time you have the buffs. Your statement has zero evidence. You only stated how the talent works through wowhead.
> 
> Wotlk Classic had the exact same "feature", but most likely you didnt even test it there .

https://www.wowhead.com/forums/topic/rolling-corruption-an-overview-162195

**Comment by crabcakeowo** [comment]
The thread that you are linking to is saying that corruption scaling for haste and spellpower is dynamic whereas Critical % chance and % percentage damage bonus are only recalculated if you press corruption. So what is your argument here?

**Comment by Scolix9** [comment]
Do you understand what rollover means? You can literally make use of the haste + SP buffs during the uptime on them (because that is how it is supposed to work) plus u can "snapshot" them with drainsoul (if u cast it just before it expires) to get a full duration or however long you wanna keep the drainsoul cast up.

**Comment by Sketish** [comment]
The stats that do not roll are:
Spellpower
Haste

Please read first

> The thread that you are linking to is saying that corruption scaling for haste and spellpower is dynamic whereas Critical % chance and % percentage damage bonus are only recalculated if you press corruption. So what is your argument here?

The stats that do not roll are:
Spellpower
Haste

Please read first

**Comment by crabcakeowo** [comment]
Do you even understand what it means to roll? It means that its kept throughout the entire fight. But clearly you are clueless on what the thread is even saying

**Comment by crabcakeowo** [comment]
Its ironic that you are asking people to read first when you don't even understand the contents of what you are reading. Absolute too

**Comment by crabcakeowo** [comment]
tool

**Comment by crabcakeowo** [comment]
Not rolling means it is dynamic, and that it gets updated everytime everlasting affliction is applied via shadowbolt/haunt/drain life/drain soul.

**Comment by crabcakeowo** [comment]
Which is correct because everlasting affliction does not snapshot haste and spellpower.

**Comment by WhitemaneIsa** [comment]
@crabcakeowo don't spam. One comment, not 5.

**Comment by Rowern96** [comment]
how is this getting "fixed" in 7 hours and we still wait for inferno fix with way more evidance?

**Comment by Steadydnt** [comment]
I love it how this dude is posting that link: https://www.wowhead.com/wotlk/guide/classes/warlock/affliction/dps-rotation-cooldowns-abilities-pve#standard-rotation
When its saying exactly this one: 
![image](https://github.com/user-attachments/assets/e7e06eb5-0c16-4a2a-bef8-5922708a426f)
Spellpower, Crit and Haste are recalculated on REFRESH

**Comment by Steadydnt** [comment]
@Rowern96  you are so right. Infernal still doing 50k damage max in Full duration. When it should be doing like 120k in a full duration in this Topic was like "HIGH PRIO" for already 4-5 weeks. And this dude just spreading wrong information because he is bald in his brain gets approval after a few hours xD. He litteraly wants warlocks to spent most their Globals on re-applying Corruption. Its so sad.

**Comment by Sketish** [comment]
What I mean:

When you cast shadowbolt/haunt/drain Corruption spell is refreshed  and holds all external buffs you  get tricks/pi/potion and debuffs on enemy target during applying.

So you snapshot corruption at start and at 35% due to talent. If you recieved any additional buff you have to recast as example
https://youtu.be/eSahjbhTeMY?t=36

**Comment by Manpower99** [comment]
Idk man just get your playtester role revoked or something this is embarrasing

**Comment by UltraNix** [comment]
https://www.wowhead.com/forums/topic/rolling-corruption-an-overview-162195
`What this means is that if we can push our Crit chance and damage buffs as high as possible when we cast the initial Corruption on a boss fight, that high chance will continue for the full length of the fight or for as long as we can keep it refreshed.`
It's clear. Crit/dmg multipliers should be constant from the very start of application.

https://www.wowhead.com/wotlk/guide/classes/warlock/affliction/dps-rotation-cooldowns-abilities-pve#standard-rotation
`It should be stated that damage % modifiers on the target are dynamic and update DPS upon application and when they fall off again, they do not roll over. Spell power and haste snapshot on refresh from Everlasting Affliction, but do not roll over.`

https://web.archive.org/web/20100717061617/http://elitistjerks.com/f80/t37900-dots_you_affliction_warlock_thread/#Rolling_Corruption_Crits_and_Modifiers
`When Corruption is refreshed, the crit rating is not updated to the actual crit rating of your character or the actual crit debuffs on the mob. Instead, the crit rating you had when you applied the first Corruption keeps "rolling" as long as you keep refreshing it`

Everything is clear here - the report is false.
The change will be reverted and not applied to server.
Thanks all for your quick reponse.
Closing.

**Comment by Steadydnt** [comment]
> What I mean:
> 
> When you cast shadowbolt/haunt/drain Corruption spell is refreshed and holds all crit and %spellpower buffs and each cast of sbolt/haunt/drain updates spellpower and haste with buffs like eradication
> 
> So you snapshot corruption at start and at 35% due to talent. If you recieved any additional buff you have to recast as example https://youtu.be/eSahjbhTeMY?t=36

Due this example I can explain it for your personal knowledge. 
Like we talked about Crit/Spellpower/Haste from procs that would be automaticly upgrade your corruption by "Everlasting Affliction" refreshes and we talked about these few "exclusive" buffs that wont upgrade your corruption automaticly from "Everlasting Affliction" like Drain Soul/Shadowbolt/ Haunt/ Drain Life.
THESE EXCLUSIVE Buffs will need you to Re-APPLY a new Corruption. These EXLUSIVE BUFFS are always either a Raid - Encounter BUFF oder DEBUFF and not from personal gear/procs/talents (EXCEPT Deaths Embrace execute talent and TRICKS OF THE TRADE rogue buff)
And since we are in Wotlk there are not many of these EXCLUSIVE buffs so I can list them all here for you so you will know in future:

Tier 7 = Loathebs 50% Crit  Spore Debuff /// Thaddius 120-130% Dmg Polarity Stack Debuff /// Malygos 50%dmg Spark of Power Debuff.

Tier 8 = Iron Council 50% Rune of Power Debuff /// Vezax 100% Dmg Shadow Crash Debuff /// Freyas 25%Dmg Potent Pheromones Buff (Shrooms)

Tier 9 = There are none in Tier 9 aka Trial of the Grand Crusader.

Tier 10 = 100% Dmg Bite of the Bloodqueen Debuff.

That are all summarized Buffs/Debuffs out of all Raid Encounters in Wrath of the Lich King that require you to Re-Cast Corruption or any Dots to be updated with the Values of each. Thank you for reading this.
