### ISSUE TITLE
Ulduar-PTR XT and Hodir

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1707]
- Hodir's Moonlights previously had a very small radius and now its abit bigger than it should be.
 https://youtu.be/j7TcxJY1VQw?si=4F0Lyol0hfGx-BHd&t=59 you can see in tankspot vod he gains the moonlight buff right after his hitbox is within the moonlight. same behavior as many og and classic videos. you have to be inside the beam or at the very edge of it but not outside of it.

 - XT's Tympanic Tantrum should be hp percentage based physical damage that ignores armor, but still able to be reduced by damage reduction auras. you can see the damage taken of hundreds of warcraftlogs and the result is the same across all logs [Proof](https://classic.warcraftlogs.com/reports/nRY72Fa3LHDT1WQg#fight=8&type=damage-taken&source=8&target=118&ability=62775&view=events)

**Comment by NickZedd** [comment]
I'm gonna make a general suggestion and I'm making it here because I don't believe devs are reading discord suggestions.

You should not obsess about making the content exactly the same as it was on retail, given how different this server already is. Leaving unintended buffs in on heroic may be desirable, if they increase the difficulty without creating some unpleasant gameplay side-effect. The reason for this is that we will have more gear, so in effect the content will be easier.

Pre-nerf is coming out during week 2, meaning that from the get-go, more gear will be available to players. On top of this, gearing will be easier because of Echoes, and the incrementing 5% buff will be added later (Unless that's changed since the leak?)

That said, the report is absolutely correct otherwise. I just find things such as changing the tantrum damage to be unnecessary since overall, the server is not blizzlike.

**Comment by Manpower99** [comment]
I do not agree personally bugs are bugs and not nerfs. leaving it in its bugged state for Heroic Difficulty is up to the devs ,which as NickZedd suggested could prove to be a nice buff to the content for those who wish to play on that difficulty.
However on Normal Difficulty (blizzlike) Tympanic Tantrum should be reduced by damage reduction auras, while it has not been adressed or put into changelog yet so we shall see their response.

**Comment by Afgann** [comment]
fixed
