### ISSUE TITLE
[Critical Issue] Multiple Paladin Aura Stacking Logic

### ISSUE THREAD

**Issue by sputnikk** [gamefreedomgit/Frostmourne#1757]
There are two critical issues that were caused by lack of rules added when the "multiple paladins allowed on same aura" fix was done back in beta. These bugs apply to all auras and everything related to auras(Aura mastery)

1. When multiple paladins are on the same aura, the group will only benefit from the aura that was applied FIRST, except the paladins themselves which use their own aura. - **this is the core issue that causes both bugs**
For example, if X has improved devo aura, Y has non improved, but Y used devo aura first and X used it second - the entire raid will use non improved devo aura except for X.

**HOW IT SHOULD WORK**: Regardless of how many paladins are on an aura, the strongest one(through improved aura talents) should apply to the whole raid INCLUDING paladins who are using a weaker version.

2. Related to 1. Aura mastery is becoming useless because of aura applied first logic.
For example, if X was the first person on aura and Y goes second on that aura, the whole raid will be affected by X aura except for Y.
Now if Y does aura mastery only Y will benefit from Y's aura mastery instead of the whole group.

**HOW IT SHOULD WORK**: Regardless of how many paladins are on an aura and in which order they entered the aura, IF Aura Mastery is cast, the whole raid should benefit from the Aura Mastery benefits of that aura.

**Comment by haephaistoss** [comment]
#1498

**Comment by Manpower99** [comment]
@UltraNix 
https://github.com/gamefreedomgit/Frostmourne/issues/94
this fix during beta simply allowed players to be active on multiple auras, the real issue which is aura mastery related did not get fixed and should be as it is very important in ulduar and critical in some hardmode encounters.
sputnikk explained it perfectly.

**Comment by Manpower99** [comment]
essentially this is causing a big issue in pugs and unsuspecting raids, makes it much harder to use AM due to lack of coordination and makes bossfights like sapphiron which is already overtuned due to massively boosted aura damage even more harder since if a player does not drop the frost aura, the next aura mastery is basically useless for everyone except the caster.

**Comment by haephaistoss** [comment]
> Fixed, I will close this issue once the fix comes live.

https://github.com/gamefreedomgit/Frostmourne/issues/1498

Can you guys also fix the global one? It's rly important in every spect of the game, not just paladin auras

**Comment by sputnikk** [comment]
> > Fixed, I will close this issue once the fix comes live.
> 
> #1498
> 
> Can you guys also fix the global one? It's rly important in every spect of the game, not just paladin auras

Can you also stop spamming your completely unrelated bs on other people's reports? You seem to do that quite a lot. Instead of begging for fixes on other people's posts, kindly go spam your own post instead.

Your post is so offtopic from mine that, if paladin auras were to work right now as you're advocating against, although incorrectly, (co-existing/stacking buff from different players with only stronger one applying) it would fix both issue 1 and 2 presented on this post.

**Comment by haephaistoss** [comment]
> > > Fixed, I will close this issue once the fix comes live.
> > 
> > 
> > #1498
> > Can you guys also fix the global one? It's rly important in every spect of the game, not just paladin auras
> 
> Can you also stop spamming your completely unrelated bs on other people's reports? You seem to do that quite a lot. Instead of begging for fixes on other people's posts, kindly go spam your own post instead.
> 
> Your post is so offtopic from mine that, if paladin auras were to work right now as you're advocating against, although incorrectly, (co-existing/stacking buff from different players with only stronger one applying) it would fix both issue 1 and 2 presented on this post.

I'm not even questioning the vaildity of the paladin aura stacking part, simply pointing out that it's a global issue, not a local one. All auras (not just paladin auras that are a persistent buff) should use the same stacking logic.

**Comment by sputnikk** [comment]
@Piootrek please don't close this issue yet. The current iteration in ptr is still not fixed. What it does now is kick other paladins off the aura when stronger is active/when aura mastery is active.
Basically if someone has improved aura, other non improved will get auto kicked every time they try to go into it.

**Comment by Manpower99** [comment]
@Piootrek Slight issue with the fix as we have tested on PTR.
Basically stronger ones are overriding it and canceling the caster's Aura completely so this introduces two issues
1.If two ppl are on the same aura and one guy uses AM, it is canceling the weaker one instead of just overriding it so the guy who didnt use AM has to re-cast it.
2.if a guy has a weaker aura, a person who casts a stronger aura from talents ( example would be imp conc or imp devo ) or possibly spell rank it also cancels it so it basically completely prevents that player from being on it unless he cancels it

Essentially if you could allow the two auras to coexist, but only strongest one simply benefits everyone at the time instead of canceling other ones, if this would be introduced it would be fixed.

This technically already exists within other auras in this server so maybe look at that and introduce it here?
For example you can have Impv. Icy Talons + Windfury Totem but you will only benefit from the stronger one.
In this case it would be 
Allow Multiple of the Paladin Aura to be active, but everyone including those who are on the weaker ones would benefit from the stronger one.

**Comment by Piootrek** [comment]
I made some changes, please test it after server update.

**Comment by Manpower99** [comment]
Let us know if possible when PTR has been reset so we can check it

**Comment by Piootrek** [comment]
> Let us know if possible when PTR has been reset so we can check it
Updated

**Comment by sputnikk** [comment]
@Piootrek nothing has changed rn/ptr has not been reset to apply changes (.s info says 19hrs uptime)
Stronger aura still kicks out players from using that aura.

**Comment by Manpower99** [comment]
Yup still the same issues.

**Comment by Piootrek** [comment]
Sorry, server wasn't restarted. Try now.

**Comment by sputnikk** [comment]
Ok so this version is even more broken sadly.
Aura mastery while 2 palas on shadow aura(same strength) doesnt apply to the other.
Devo aura improved(stronger) will not let other paladins enter that aura.

**Comment by sputnikk** [comment]
Since this will probably not be resolved for Ulduar release I suggest keeping the previous version that kicked you out the normal auras when aura mastery was used. At least with that people can realize they got their auras removed, the current version makes aura mastery useless again for people who don't notice.

**Comment by Piootrek** [comment]
Please test it again after ptr update.

**Comment by Manpower99** [comment]
Will do once it gets applied

**Comment by sputnikk** [comment]
Its working perfectly now, except one important detail:
Improved auras are stacking benefit wise with normal auras:
Ex: I have 2/3 improved devo aura and other paladin has 0 improved and we get armor from both.
