### ISSUE TITLE
MPG- Flame leviathan and pyrite availability

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#1782]
on both 25 and 10, a huge lack of pyrites.
https://youtu.be/Igw96Jj1BNI?si=Nfv3ZSxzajfTVeXQ&t=57
https://youtu.be/9HG59olverY?si=2hfdqRr7E_ZOutT0&t=68

**Comment by sputnikk** [comment]
I'd like to mention the pyrites don't really move at all they are supposed to spawn from various points and patrol around the sky of the leviathan arena. This happens both before and during the fight.
Because of this movement the sky inside leviathan arena should be pretty much filled with flying pyrite to shoot down.
