### ISSUE TITLE
Algalon the Observer spawns too many Constellations in 25 Player Mode

### ISSUE THREAD

**Issue by Tetrahydrx** [gamefreedomgit/Frostmourne#1875]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Algalon is supposed to have only three constellations up max.,. It appears that currently on the server he always spawns three, no matter what, which resulted in us having 8 Constellations in the fight. Basically, there is no cap to the constellations.

**How to reproduce:**
Simulating the fight killing a constellation and waiting should work.

**How it should work:**
Should be  only 3 constellations up only, no more than that.

**Database links:**
https://youtu.be/ewxLBdYTrPg?t=4427  Algalon fight at 1:14:06 shows it pretty well

https://wowwiki-archive.fandom.com/wiki/Algalon_the_Observer

https://www.wowhead.com/wotlk/npc=32871/algalon-the-observer

**Comment by Manpower99** [comment]
Seems to be indeed the case, didnt find any retail/classic vod of more than 3 constellations.
infact some vods who were intentionally not closing black holes only one more constellation would come out to make sure theres 3 in total whenever the timer kicks in, but if theres already 3 alive and the timer kicks in, no new constellation would come to assist algalon. proving this bug report to be correct.
https://www.youtube.com/watch?v=_hG-tm99e1k is classic proof

https://youtu.be/uv_b1-bsN5o?si=mo41myyftYLH57Of&t=295 is og proof, you can see timestamped it is time for new constellations to come down but since 1 constellation was already present and wasnt used to close a black hole, only two spawned.

**Comment by oomshroom** [comment]
https://youtu.be/rdQ3eMbaIoQ?t=217
video from classic wotlk
starting at 3:37 you can clearly see 4 constellations up
![image](https://github.com/user-attachments/assets/f2693d2d-8fa6-49d6-965a-cdb985279117)

**Comment by Manpower99** [comment]
In that same video at 2:30 only two stars came down instead of 3, so there is a cap its just that something happened to reduce it perhaps at the time or a bug idk. some players on discord have mentioned it was bugging at some points during classicwotlk
or there is something else we don't really know about.
![image](https://github.com/user-attachments/assets/1823fc74-f026-490b-9997-19ece9b61d01)

**Comment by Afgann** [comment]
fixed
