### ISSUE TITLE
Mimiron - Fire Bots

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#1909]
The fire bots are simply way too efficient and strong on clearing fires here - a group of 3-4 of them are full cleansing the fires in mere moments and there will be zero fire left, then they instant cleanse the new fires that spawn.

On classic they suck (by design) - they do clear fires but very inefficiently - they do one patch then move across the room to do another patch and etc. Maybe just start by adding a longer cooldown to their water spray.

See video:
https://www.youtube.com/watch?v=_Bab3749jiU&t=345s&ab_channel=SubtleFW

**Comment by NickZedd** [comment]
In the video you can see that they have nearly no cooldown on water spray though. They can put out fires very quickly, but it is dependent on how spread out they are and on rng. The reason they have tons of fires is because they are killing off the bots.

Looking at this video https://www.twitch.tv/videos/2250136137?t=1h2m30s the behavior on whitemane seems very similar.

In the classic video, the bots sometimes seem to be moving slower but I don't believe that's because they function like that. It's because of player abilities.

**Comment by Godmatik** [comment]
Huh? The video I shared you can see 3 firebots are clearly alive and clearing, just doing so fairly inefficiently and slowly. Compared to Whitemane, those 3 firebots full clear the fire in less than 15 secs.

Having done this fight on classic numerous times - I can tell you for certain the fire bots are about 2x more speedy + efficient compared to there.

**Comment by NickZedd** [comment]
I definitely don't see the differences you're talking about between whitemane and classic. The bots can run all the way across the room on Whitemane as well, and you do see them run with high movement speed on classic just not every time.

Idk why I'm arguing about this though. I'd actually prefer if it was harder here than classic.

**Comment by Afgann** [comment]
fixed
