### ISSUE TITLE
XT HC Health 25man

### ISSUE THREAD

**Issue by jonathansbb** [gamefreedomgit/Frostmourne#1914]
There has been made more then one bugreport on this and also changes. My guild has done this boss quite alot now and we kinda deem it impossible to kill at the current state.

**Current state of XT:**
1. 10min Enrage i.e, 600 seconds
2. Spark every 10 seconds with 360k health, if we say that 50 sparks will spawn that would be around 18million HP just in sparks
3. HP to activate heart: 5.5mill
4. HP on heart: 10 mill
5. HP after heart is dedge: 72 million

**These together amount to 105.5million HP that the group has to spank. Average DPS requirement per DPS (with 0 deaths):**
1. 19 DPS: 9.3k DPS avg. dps for 10mins straight
2. 18 DPS:  9.8k DPS avg. dps for 10mins straight

Not sure this is possible even with full Ulduar BIS. I understand that its supposed to be challenging but right now the sheer HP pool on this boss makes it (possibly) impossible to kill. If we compare it to Classic now (where they had 252 ilvl MIND YOU) the HP after heartbreak was 47,5 million, which is only 2/3 of current tuning. (see below for both retail and Wotlk values. This HP pool combined with the struggle to actually stay alive will be extremely difficult if not impossible (3rd time i say impossible, i know)

**Suggestion:**
1. tune HP after heartbreak to same as Wotlk classic i.e., 47,5 million health. This health with the custom buffs on sparks and debuffs will make this more then challenging and most guilds will most likely never be able to kill even with that.

**Small edit to suggestion:** enrage timers were not the same so suggestion to reduce the hp with the same coefficient doesn't make sense I guess. However, the encounter was deemed unkillable even there and got nerfed two weeks in, also worth mentioning that this nerf was too high, which means we should be somewhere in between here. So setting HP-pool after heartbreak to around 60mill with an 10minute enrage timer might make more sense. Equivalent to 165% bonus health from heartbreaker.

**Here are also values for Post-nerf and Pre-nerf for both Retail and Classic Wotlk:**

**Patch 3.1.0 (2009-04-14)**
Base HP: 22.5M
HM HP: 40M
Heart HP: 10M

**Patch 3.1.2 (2009-05-19)**
Base HP: 22.5M
HM HP: 36M (-10%)
Heart HP: 8M (-20%)

**Patch 3.1.3 (2009-06-11)**
Base HP: 22.5M
HM HP: 36M
Heart HP: 7.2M (-10%)

**Classic**
Patch 3.4.1 (2023-01-19)
Base HP: 25M
HM HP: 47.5M
Heart HP: 10M

**Patch 3.4.1 (2023-01-31)** 
Base HP: 18M (-28%)
HM HP: 25M (-47%)
Heart HP: 5.4M (-46%)

Links:
https://clips.twitch.tv/HeadstrongRacyWalletGingerPower-D6bagvYyYW9dIJ5J
https://www.reddit.com/r/classicwow/comments/10qfotu/xt_hard_mode_nerfed_from_475_mil_hp_to_25m/

**Comment by Manpower99** [comment]
For one i never saw the appeal of making Tympanic Tantrum custom and not reduced by damage reduction auras, but previously that was because this encounter was thought of as "killable" by Frosthold tuning standards, nevermind that frosthold XT was not fully Pre-Nerf and that classes at the time were buggy and doing more damage than they are now, in addition to many exploits being abused that most are no longer present, it is simply not the same realm and things are very different.

However i do not think its a good idea to nerf it to the fkn ground like Classic did, 25HC XT should either remain same as current HP or if its unkilled for too long (4 IDs ) just reduce heartbreak HP to Patch 3.1.2 Values.
tyvm.

**Comment by jonathansbb** [comment]
> For one i never saw the appeal of making Tympanic Tantrum custom and not reduced by damage reduction auras, but previously that was because this encounter was thought of as "killable" by Frosthold tuning standards, nevermind that frosthold XT was not fully Pre-Nerf and that classes at the time were buggy and doing more damage than they are doing now, in addition to many exploits being abused that most are no longer present, it is simply not the same realm and things are very different now.
> 
> However i do not think its a good idea to nerf it to the fkn ground like Classic did, 25HC XT should either remain same as current HP or if its unkilled for too long (4 IDs) just reduce heartbreak HP to Patch 3.1.2 Values. tyvm.

If anything this should be gradually nerfed rather then nerfing it too the ground in one go. But as a starting point 72 million is just too high, basically unkillable, no gear will be enough in current patch to make up the dps gap from actually killing this thing. 62 million, however, is a HP-pool that you can actually have a shot at killing.

**Comment by Godmatik** [comment]
Seems like every private server and even Blizzard goofs up heavily on this fight specifically with the overbuffing. Problem here though is that this is required to access HC Algalon (correct?)

So yeah, need to nerf the HP so that it is more reasonable. In Blizzard's case they just nuked the HP but they waited quite a few weeks to do so, literally zero guilds were able to kill it.

**Comment by gforghieri** [comment]
nerf the HP, XT heroic shouldnt be hardest boss, gatekeeping the RF.

Lets start with some gradual nerf of hp of like 20% and go from there.

**Comment by jonathansbb** [comment]
Honestly, HP is still 72million this is just stupid @RadeghostWM @UltraNix @Afgann. IT CANNOT BE KILLED.

**Comment by Godmatik** [comment]
Yeah its simply impossible right now
