### ISSUE TITLE
Ulduar 25m hc XT, searing light and gravity bomb is spawning too fast

### ISSUE THREAD

**Issue by gforghieri** [gamefreedomgit/Frostmourne#1942]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

Boss is casting these debuffs on players without any cooldown. 

Just checking if this is intended?

The result is too many life sparks with a lot of HP which coupled with the overtuned HP of the boss makes it unkillable at the moment.

I do not see anything regarding the frequency of how fast the boss should cast these abilities, which means it should be the same as normal hardmode.

![image](https://github.com/user-attachments/assets/e0cb5f10-1d22-4a12-95eb-dc6d117ff266)

https://archive.is/6WwGI

**Comment by jonathansbb** [comment]
The frequency of bombs and searing light is intended. Can't find the report about right now, but there is one somewhere.

**Comment by Manpower99** [comment]
This is one of the reasons why frosthold was not infact truly pre nerf imo since the timer at the time was simply post nerf.
(2009-06-11): The XT-002 Deconstructor encounter has received the following changes: the health of the heart has been slightly reduced in heroic difficulty and the rate at which Gravity Bomb and Searing Light are cast has been reduced.
https://www.youtube.com/watch?v=GYBu_hQK1Po

You could argue the difficulty is massively increased due to this and could be adjusted, but it is intended yes.
