### ISSUE TITLE
Healing Wave not instant if used too soon after Natures's Swiftness - Shaman

### ISSUE THREAD

**Issue by broizter** [gamefreedomgit/Frostmourne#1943]
This started happening in the last week or so.
https://www.wowhead.com/wotlk/spell=16188/natures-swiftness

**Comment by Aeradel** [comment]
Adding needed context:

I could not replicate this with any heal other than Healing Wave. I included a video of a sample of testing I preformed to better help the developers assess the bug.

I used a macro to cast both Nature's Swiftness and Healing Wave at the same time, and that causes an issue, but isn't reliable replication. It can still work, it's just random if it does or not. The same also happens if you hit the buttons manually. It would also seem that the buff ignores Healing Wave, but then after several casts uses the buff as it should. 

https://youtu.be/ODPrwzZ5ioc

Kind of a poor video, but you get the idea of the issue. 

If you're able to replicate this with any heal other than Healing Wave, please document in a video. @broizter

**Comment by broizter** [comment]
I can confirm I've only been able to trigger it with Healing Wave.

**Comment by Riztazz** [comment]
It looks like one of those issues that takes 2 days to debug for a 1 line fix :/ wish me luck, jumping in

**Comment by Aeradel** [comment]
> It looks like one of those issues that takes 2 days to debug for a 1 line fix :/ wish me luck, jumping in

Good luck soldier :saluting_face:

**Comment by Riztazz** [comment]
Thanks for the video, it helped a ton, figured out what's happening

**Comment by Riztazz** [comment]
Fixed, will close once it's live
