### ISSUE TITLE
[PALADIN] Hand of Sacrifice DMG Transfer doesn't work further than 30 y away

### ISSUE THREAD

**Issue by haephaistoss** [gamefreedomgit/Frostmourne#1954]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:** Hand of Sacrifice is a friendly buff that has a cast range of 30 y. If already on a target, the dmg splitting should happen until the buff fades from said target. Currently splitting stops if the caster is further away than 30 y from the target.

**How to reproduce:** Cast HoS on a friendly target, and move away, further than 30 y

**How it should work:** If the buff is on the friendly target, as long as the 2 players remain within visible distance to each other dmg should be split, regardless of distance.

**Database links:** https://www.wowhead.com/wotlk/spell=6940/hand-of-sacrifice

**Comment by NickZedd** [comment]
I'm fairly certain I remember this being the case on warmane as well. No idea about classic. Should be double checked before being changed imo.

**Comment by haephaistoss** [comment]
I don't honestly think there is a private server out in the open with worse scripting in terms of spells than warmane. If we take that as a basis, we've reached rock bottom, the only way is up from there.

Classic is not original wrath either.

In og wrath there never was a range oimit on split dmg, unless it was provided by an aura like ability - Dsac.

 It is a buff, that simply works, once cast.

On the flip side, there is no evidence anywhere that it should have a max range for transferring DMG. 

Don't you think if it would have such a short range, it would be mentioned all over the internet?

**Comment by NickZedd** [comment]
Hey I missed the reply, my bad.

I mentioned classic since it's usually easier to find good info on that rather than retail.

I don't think it would be mentioned very often at all as it's a very niche thing that only some people would notice in the first place. That said, if one were to do an extensive search and not find anything we could probably conclude that it wasn't limited by range.

By the way, there's another "issue" with hand of sacrifice and divine sacrifice that I noticed but haven't researched to find out how it worked originally. Basically, you can't use Hand of sac if there is already divine sacrifice on the target. Using Hsac first and then Dsac does work however.

Do you know anything about this?

**Comment by Afgann** [comment]
fixed
