### ISSUE TITLE
Mage Slow Fall should stack Illustration 

### ISSUE THREAD

**Issue by bandini9** [gamefreedomgit/Frostmourne#1995]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Mage Slow Fall should stack Illustration  just like Priest Levitate

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by Piootrek** [comment]
Any proofs?

**Comment by oneadanut** [comment]
![image](https://github.com/user-attachments/assets/621a7622-e5a6-40ab-a6d3-714b0f7749cf)

You might want to revert the Levitate one.

**Comment by Manpower99** [comment]
Both interactions definitely did work in classic wotlk.
![image](https://github.com/user-attachments/assets/026fdb60-c235-4e8c-a87c-5a4452e51360)
Wether or not it is indeed the intended 3.3 way of working or not IDK, but likely it is the case since tooltips can often be misleading due to blizzard being blizzard lol.

**Comment by Piootrek** [comment]
Fixed, I will close this issue once the fix comes live.
