### ISSUE TITLE
Hand of Reckoning Damage Not Triggering When Used After Exorcism (Paladin)

### ISSUE THREAD

**Issue by Aar0nzy** [gamefreedomgit/Frostmourne#2115]
**Description:**
When playing as a Paladin, if Exorcism is used and Hand of Reckoning is spammed during the Exorcism cast, the damage from Hand of Reckoning does not occur when initiating combat with an enemy NPC as intended. Exorcism's damage triggers correctly, but the damage from Hand of Reckoning is missing entirely.

**How to reproduce:**
1. Play as a Paladin and ensure you have both Exorcism and Hand of Reckoning available.
2. Target an enemy that is out of combat and cast Exorcism.
3. Immediately spam Hand of Reckoning after casting Exorcism.
**Note:** Spamming Hand of Reckoning while Exorcism is casting will trigger the spell queue system, which should result in both Exorcism and Hand of Reckoning landing at the same frame time when Exorcism finishes casting.
4. Observe that while Exorcism deals damage as expected, the damage component of Hand of Reckoning does not occur.

**How it should work:**
After casting Exorcism, if Hand of Reckoning is used on an enemy target that is out of combat, both spells should trigger their respective damage effects. Hand of Reckoning should deal its intended damage along with Exorcism, as they do not share any conflicting mechanics that should prevent Hand of Reckoning from working.

**Database links:**
[https://www.wowhead.com/wotlk/spell=879/exorcism](url)
[https://www.wowhead.com/wotlk/spell=62124/hand-of-reckoning](url)

**Comment by OrceMaceski** [comment]
Imho, that should be the intended behavior. Hand of Reckoning states that it will deal the damage component IF a mob is not targeting you. Now, if you cast Exorcism first to an unfriendly attackable tauntable mob that is not in combat, it basically puts it in a state of combat and targeting you and therefore not dealing the damage component of the Hand of Reckoning if you cast it after.
What you are describing here is taking advantage/exploiting of the client/server latency

**Comment by Aar0nzy** [comment]
@OrceMaceski Thank you for your input. I understand your point of view regarding the interaction between combat initiation and Hand of Reckoning's damage trigger, but I respectfully disagree with the interpretation that this behavior should be considered an exploit or unintended interaction.

To clarify, while Hand of Reckoning's damage component only applies when the target is not actively targeting the player, the situation described here leverages the spell queuing system as intended by the game’s mechanics. The spell queue system, which is part of the game's core design, allows for two abilities to be cast in rapid succession, with both executing almost simultaneously at the moment Exorcism finishes casting. As a result, the Hand of Reckoning damage should still apply, as the enemy should not have initiated its targeting of the player before the queuing resolves.

This interaction aligns with the "blizzlike" experience, where players frequently take advantage of the spell queue system for smoother combat flows, especially in latency-sensitive scenarios. The purpose of the spell queue is to prevent missed inputs and enhance gameplay responsiveness. Therefore, this should not be perceived as an exploitation of latency, but rather a legitimate and intended consequence of the queueing mechanic.

Furthermore, Exorcism does not immediately put the enemy in combat or cause it to target the player the moment the cast begins, but only upon damage application. If both Exorcism and Hand of Reckoning hit at the same time, there is no conflict preventing Hand of Reckoning from applying its damage.

In summary, the behavior I'm reporting does not involve circumventing game mechanics or exploiting latency; instead, it is an example of using the game's built-in systems as designed. I believe the reported issue revolves around Hand of Reckoning's damage failing to trigger when it logically should under these circumstances.

Thank you again for taking the time to discuss this. I appreciate the attention given to refining these interactions to maintain a faithful experience.

**Comment by OrceMaceski** [comment]
@Aar0nzy I completely get your point, and its how it was back in the original wotlk days, the spell queue system back in the days was implemented due to hardware limitations and you would often see, for example, people polymorphing eachother at the same time when dueling due to spell queueing. In later iterations/expansions of the game spell queing window was reduced significantly (or maybe removed, can't remember and too lazy to check). Now if this server wants to reproduce the original wotlk experience thats totally fine, I'm just saying, logically, if it werent for the spell queue then this behvaior is working as intended. Besides, I play as prot pala so having extra damage benefits me ^^

**Comment by scrublama** [comment]
First off, you’re twisting the concept of the spell queuing system to fit your narrative. The system is designed to smooth out gameplay, not to create loopholes where spells exploit timing in ways that clearly go beyond their intended design. The fact that you're trying to use it as a justification for triggering Hand of Reckoning’s damage—on an enemy that’s actively switching to target you—is nothing but mental gymnastics.

The core design of Hand of Reckoning is crystal clear: the damage ONLY procs when the target is NOT targeting you. The moment you cast Exorcism, the enemy is engaging in combat with you, even if the damage doesn’t apply until the cast finishes. You can't cherry-pick parts of how combat initiation works, pretending there's this magical moment where the enemy is “technically” not on you, just to squeeze in a burst of extra damage. That’s not what “blizzlike” is about. You're basically arguing to abuse a technicality that was never part of the spirit of the game.

Let's get real about this “smooth combat flow” argument too. The spell queuing system exists to improve input responsiveness, not to create some janky, frame-perfect window where you can squeeze in abilities in ways the developers never intended. Trying to frame this as a legitimate mechanic is laughable, and everyone who understands how the game works can see that. You’re bending the system to fit your goal and calling it “intentional” when it’s just an unintended consequence of the queuing system’s existence.

And let’s address your point about Exorcism not immediately putting the target in combat. Yes, the combat doesn’t technically start until the damage lands, but so what? The reality is, the moment that Exorcism hits, the target is now engaged with you. The game doesn’t care about your hyper-technical distinction about the exact nanosecond the enemy switches to target you—the fact is that once that happens, Hand of Reckoning is supposed to stop dealing damage. Period. You can’t exploit the system’s responsiveness and call it “intended,” because that’s exactly what this is: an exploit.

So no, this isn’t just some innocent interaction of the spell queuing system. It’s a clear case of you abusing mechanics that were never designed to interact in this way. This kind of argument doesn’t stand up when you look at the big picture, which is why this behavior needs to be addressed—and fixed—to maintain the integrity of the game.

**Comment by scrublama** [comment]
This really should have been a game design question for someone like Radeghost, not something you developers just blindly implemented without a second thought. I mean, seriously, why was this even greenlit? It’s obvious that no one with an eye for balance or actual game flow signed off on this. Instead of thinking through how this interaction fits into the bigger picture of class mechanics, it feels like a rushed decision that completely disregards how players are actually using these abilities.

You developers went ahead and changed something without even consulting the people who understand how these systems were supposed to work. If someone like Radeghost had a hand in this, they’d have caught this inconsistency immediately, instead of leaving players to clean up the mess after your half-baked fix went live.

**Comment by Afgann** [comment]
> This really should have been a game design question for someone like Radeghost, not something you developers just blindly implemented without a second thought. I mean, seriously, why was this even greenlit? It’s obvious that no one with an eye for balance or actual game flow signed off on this. Instead of thinking through how this interaction fits into the bigger picture of class mechanics, it feels like a rushed decision that completely disregards how players are actually using these abilities.
> 
> You developers went ahead and changed something without even consulting the people who understand how these systems were supposed to work. If someone like Radeghost had a hand in this, they’d have caught this inconsistency immediately, instead of leaving players to clean up the mess after your half-baked fix went live.

Changes don't go live instantly after they appear on discord.
