### ISSUE TITLE
[PTR] TOC valkyrs are too high up in the air unhittable, their hitbox seems to be changing growing with their stacking buff

### ISSUE THREAD

**Issue by gforghieri** [gamefreedomgit/Frostmourne#2393]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

[PTR] TOC valkyrs are too high up in the air unhittable, their hitbox seems to be changing growing with their stacking buff

**Comment by NickZedd** [comment]
The stacks might have something to do with it, but I'm not sure. It's definitely not the only reason. Here's what I've figured out so far:

- Moving a boss always makes it fly higher and higher as it moves.
- The bosses usually stay at the same elevation if the tank stands still (the tank should not stand still though due to orbs)
-  If the tank moves but stays within range of the bosses, they will occasionally move upwards, bit by bit, until they can not longer be reached.
- Sometimes, when the bosses cast abilities, they will change their elevation significantly, either up or down. Couldn't replicate this but saw it very clearly multiple times on one pull.
- If the tank moves out of a boss's melee range very slightly at just the right angle, it will go all the way back down to the ground.

**Comment by Piootrek** [comment]
Fixed
