### ISSUE TITLE
Swing speed bug after new patch

### ISSUE THREAD

**Issue by Gajoel14** [gamefreedomgit/Frostmourne#2471]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
My warriors swing speed has gone absolutely bonkers. 

**How to reproduce:**
Dnu

**How it should work:**
Have normal swing speed

**Database links:**
![{1F40FCF5-8511-4E53-B1F3-CF7E19193A25}](https://github.com/user-attachments/assets/724ad740-4a6d-451a-8bd0-35a05c66e7cb)

**Comment by Gajoel14** [comment]
My dmg is equally bad. It is not a visual bug

**Comment by sputnikk** [comment]
This is not a new patch/client bug. This is a bug that happens ONLY IN Black temple timewalk, also might be a recent only thing or I just didnt notice before.

Basically the trash mobs nagas in BT timewalk use a hurricane spell that slows attack speed. What I assume is that spells keeps ticking in the background making your attack speed increase indefinitely even after stepping out of the AoE - spell id:40090. (might be different id this is from nontimewalk BT)

I noticed this bug after/during Najentus kill last week, theres a chance something else causing it but this seems the most likely
@Piootrek

**Comment by Gajoel14** [comment]
Oh well. Still super duper frustrating ^^

**Comment by Piootrek** [comment]
Do you have any video of this? I cannot reproduce, my speed goes back to normal after stepping out of the hurricane.

**Comment by sputnikk** [comment]
I cannot guarantee the hurricane is what causes it, just a personal guess.
What I can guarantee is that something between BT entrance and Najentus (including boss) is causing it. (half my raid got it during last clear, half didn't - I personally noticed it happening before najentus fight as I was gaining no rage due to slow atks)
Also high chance I will never do BT in the future so cannot provide video, theres also a chance that its a LIVE bug only and might not be replicable on PTR.

Another thing - this bug works as an infinite tick, whenever it ticks your attack speed goes slower until you theoretically never attack. You can notice this on your character tab ( 2.6 atk speed then after a few seconds -> 3.8 -> 4.8)
Relogging fixed this bug for me, **but other people claimed it did not fix it for them**.

**Also**, there's a high chance someone motivated enough can figure out how to reverse this process from slowing your attack to speeding your attacks infinitely. Just waiting long enough with this bug might cause buffer overflow and make you oneshot things.

**Comment by sputnikk** [comment]
pic a few seconds before the "tick"
![WoWScrnShot_112024_225456](https://github.com/user-attachments/assets/c040efcc-8aa9-46e3-bcfe-a4a788baf91e)

pic after the "tick", it kept going higher and higher until i relogged
![WoWScrnShot_112024_225504](https://github.com/user-attachments/assets/edc7091d-e689-4ceb-b85b-7c358b9d0b21)

**Comment by Piootrek** [comment]
Should be fixed after next server uptdate.

**Comment by Firalus** [comment]
> Should be fixed after next server uptdate.

@Piootrek does the fix take into account player-cast Hurricane? This bug is most likely the cause of the recent Discord drama discrediting In Harmony for their Anub kill, as they had a druid use Hurricane to cleave on the adds.

**Comment by Piootrek** [comment]
> > Should be fixed after next server uptdate.
> 
> @Piootrek does the fix take into account player-cast Hurricane? This bug is most likely the cause of the recent Discord drama discrediting In Harmony for their Anub kill, as they had a druid use Hurricane to cleave on the adds.

Yes, it fixed that issue too
