### ISSUE TITLE
Quest : Springing the trap

### ISSUE THREAD

**Issue by KryndorX** [gamefreedomgit/Frostmourne#2490]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
When you use the quest item on "Unlit signal fire", the roleplay will start but after the roleplay end, they just disappear.

**How to reproduce:**

**How it should work:**
The quest must progress and not just reset after roleplay.

**Database links:**
https://www.wowhead.com/wotlk/quest=11969/springing-the-trap

**Comment by emirie1** [comment]
I believe that this is caused by Keristraza spawning up in the air a far distance from the signal fire where you use the quest item as shown here:
![WoWScrnShot_120124_174651](https://github.com/user-attachments/assets/20b601c6-ac82-4ce1-9328-f0d6425f24fa)
She is supposed to spawn and fly down next to the signal fire and then land as she has some "say" dialogue that you are supposed to be able to hear. You can still hear this dialogue if you go over and stand under where she is in the air, but when the quest goes to put you on her back to progress the objective, it instead pops up with the message "You are too far away from the taxi stand!" which would be the signal fire. When you just stand next to the signal fire, nothing happens at all.

What is supposed to happen is that you hop on Keristraza's back and fly up to see the image of Malygos in the air being pelted by red drakes and doing nothing until you get back down to the ground. Once on the ground, Malygos will come down and freeze Keristraza and take her off into the Nexus.

**Comment by Riztazz** [comment]
fixed, will close once it's live
