### ISSUE TITLE
Raid IDs

### ISSUE THREAD

**Issue by Amine-x-x** [gamefreedomgit/Frostmourne#2584]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
If you join a raid and enter the instance, then you leave (before encounter start of any boss even first boss) then the raid you left continue the run and kill the bosses, you get id.

**How to reproduce:**
Join raid, leave before they even pull , go check after boss die.

**How it should work:**
The only players that must get id , the ones that was there during boss encounter (even if they leave during it) and the players who did stay until boss die , and the players who joinned after boss die. not who left before they even start.

**Database links:**

**Comment by Piootrek** [comment]
It's not possible. Only players from the same map can be bound to the instance.

**Comment by oneadanut** [comment]
The thing is, the raid gets id after killing Gormok, but not killing Worms or Icehowl, which I found that it worked this way in classic, but tbh it's a bad feature and shouldn't be applied on private servers since we have shared id and custom heroic toc. Warmane didn't put id after killing one of the beasts, only after finishing encounter killing Icehowl.

Pioo, you need to check if a person gets the popup for accepting id if those above happened.
