### ISSUE TITLE
Glyph of Explosive Trap has a wrong value

### ISSUE THREAD

**Issue by Tednugg** [gamefreedomgit/Frostmourne#37]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/) https://www.wowhead.com/wotlk/spell=63068/glyph-of-explosive-trap#modifies
[//]: # (wotlk-twinhead.twinstar.cz) https://wotlk-twinhead.twinstar.cz/?spell=63068

**Description:**
Glyph of Explosive Trap allows Explosive Trap to deal a critical strike but only for a 50 % of the value resulting in 150 % of the normal damage instead of 200 %

**How to reproduce:**
Apply glyph of explosive trap, go to a dummy and place explosive trap, observe the damage. For me it ticked for 348 normal damage and crit for 522 which is exactly 1.5 multiplier (https://imgur.com/a/a0PveAw)

**How it should work:**
Glyph of Explosive Trap should allow Explosive trap to Critical strike for 100 additional value
Please check wowhead link below for reference, I also included a link to warcratlogs, where it's clearly visible that trap launcher cirts for 200%.

**Database links:**
https://www.wowhead.com/wotlk/spell=63068/glyph-of-explosive-trap#modifies

https://classic.warcraftlogs.com/reports/fRVHgp3dThaWrjJ4#fight=20&type=damage-done&source=31&ability=49065&pins=0%24Separate%24%23244F4B%24damage%240%240.0.0.Any%2472328213.0.0.Hunter%24true%2437813.0.0.Boss%24false%2449065&target=403&targetbuffs=49065.-63672.-60052.-60053.-49001&start=4959203&end=4999203

**Comment by Tednugg** [comment]
> Did you relog after applying the glyph?

Yessir, if I didn't relog it wouldn't crit at all, since explosive trap doesn't crit on it's own if it's not glyphed.

**Comment by Karsenity** [comment]
I don't have a reference on-hand, but I'm fairly certain in 2009 wotlk it was only 50% because traps are considered spells (spells only crit for 50% increased damage, rather than 100% like physical attacks do)

There was a lot of back-and-forth about this on Warmane's server because it seems like Blizzard flip-flopped between 50 and 100% a few times in original, with someone linking MMO-Champion posts days apart claiming each value. Someone on their staff dismissed it though and pasted a chat-log snippet from 2010 showing the 50% value
![image](https://github.com/gamefreedomgit/Frostmourne/assets/48289014/27e4c4ee-c5ad-4d7f-86ff-e2f5f5a269ed)

**Comment by Tednugg** [comment]
If Explosive Trap was a spell, then that would mean it's Crit chance should be affected by spell Crit chance buffs (like moonkin aura, imp scorch, focus magic) but it's not, that would also mean that it's Crits would proc Focus Magic for the mage. 
![image](https://github.com/gamefreedomgit/Frostmourne/assets/158357485/ae73c27c-20e2-482a-ad89-e683ef60a813)
And here you can see that's clearly not the case.

**Comment by danniellos94** [comment]
Karsenity is right it was orignally 50% increased, it was fixed on wotlk classic and aggrend said they would consider that as a bug in 2008 if they would know about it. This is now to be decided to whitemane stuff but I would imagine if the dev assigned this as a bug in wotlk classic it should be fixed most likely.

**Comment by Karsenity** [comment]
I don’t think all spells actually benefit from those effects due to just inconsistencies in the game.

For instance thunderclap is well-known because it does physical damage, but is actually a spell (meaning when you silence warriors, they’re blocked from casting it)

Traps worked similarly, I know in classic they at least used the spell hit table and therefore had the chance to be resisted.

**Comment by danniellos94** [comment]
https://github.com/JamminL/wotlk-classic-bugs/issues This is the wotlk classic github for reference can check the explosive trap crit damage that got fixed. I hope this helps.

**Comment by Karsenity** [comment]
Will be curious if they fix it. On one hand I’d love that for my hunter dps, on the otherhand that means they’d probably fix other 2009 bugs like the gargoyle delay and completely shake up class balance 😂

**Comment by danniellos94** [comment]
> Will be curious if they fix it. On one hand I’d love that for my hunter dps, on the otherhand that means they’d probably fix other 2009 bugs like the gargoyle delay and completely shake up class balance 😂

I mean it's already broken on this server gargoyle has no delay, also if this is old scripting and most likely is army on ulduar was doing 300k with snapshot on wotlk classic it was about 100k maximum.... 
Blizzard nerfed the gargoyle on wotlk classic on ulduar phase, they had no idea how op gargoyle without a delay will be.
