### ISSUE TITLE
Blue ilvl 200 BoE gear from heroics too common

### ISSUE THREAD

**Issue by Godmatik** [gamefreedomgit/Frostmourne#602]
Blue gear drop rates from trash mobs in heroics (ilvl 200 gear) is way too common.

Most heroics you will get 4-5 per dungeon.

Drop rate is simply way too high, on classic you were lucky to see one per run.

**Comment by Manpower99** [comment]
Why would droprates matter in a server with an accelerated timeline lol.
Classic had Prepatch to gather pre naxx bis from sunwell for their rogues and unholies and shamans, and a longer time to get their reps and pre raid bis items. many things should be considered QoL due to the accelerated timeline of prominent wotlk private servers.

**Comment by Godmatik** [comment]
Well if drop rates don't matter let's have each boss drop 3 items and also 3 badges?

Dumb take, everything else has proper drop rates, these should as well

**Comment by UltraNix** [comment]
Drop rates for these are increased in purpose.
