### ISSUE TITLE
[Dungeon] Ahn'kahet: the old Kingdom

### ISSUE THREAD

**Issue by Rippinz** [gamefreedomgit/Frostmourne#743]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Boss Jegoda Shadowseeker is bugged. When he does the mechanic where we gotta kill the Twilight add, he still gets the damage buff.

**How to reproduce:**

**How it should work:**
Boss should only get the damage buff if we ignore the add that buffs the boss.

**Database links:**

**Comment by Godmatik** [comment]
The issue is because the add can be thrown off course with death coils and stuns and such, then it visually goes off sync with the path it takes and gets absorbed not at the proper spot.

**Comment by Manpower99** [comment]
No i dont think it is as we killed the add and not cc it and it still got the damage buff.
the mob also moves very fast and so far in all attempts we have done it always spawns the one in the center instead of a randomized one from the spectacle.
Directly from wowpedia:
Both the amount healed and the duration of the 200% damage buff seems to be dependent on how much health the minion has when it is sacrificed. Because of this, every bit of damage on the minion helps even if the minion is not killed outright by the time it is sacrificed

https://www.youtube.com/watch?v=1qGeZzqDO3I

**Comment by Afgann** [comment]
fixed
