### ISSUE TITLE
Tailoring cloak embroidery internal cooldown

### ISSUE THREAD

**Issue by Bluecow941** [gamefreedomgit/Frostmourne#786]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
https://github.com/gamefreedomgit/Frostmourne/issues/298
Reopening the issue, it seems like after fix it still doesn't proc correctly

**How to reproduce:**
enchant them and check proc chance and icd

**How it should work:**
Swordguard Embroidery : should be 20% proc chance on hit and 55sec icd
Lightweave Embroidery : should be 35% chance on cast (can proc from other procs ) and 1min icd
Darkglow Embroidery : 35% chance per cast and 45sec icd

**Database links:**
https://www.wowhead.com/wotlk/spell=55640/lightweave-embroidery
https://www.wowhead.com/wotlk/spell=55776/swordguard-embroidery
https://www.wowhead.com/wotlk/spell=55768/darkglow-embroidery

**Comment by UltraNix** [comment]
Lightweave:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/f4dc7af8-64b1-4bdf-bbe7-70f9584b89ce)
1 min ICD.

Sworguard:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/2009fcc1-62e2-48c4-946f-583652f2da74)
55 sec ICD.

Darkblow:
![image](https://github.com/gamefreedomgit/Frostmourne/assets/80540499/0bfd6cc0-a641-4fb0-8c82-e087659d5c34)
45 sec ICD

Proc chances are correct.

**Comment by Manpower99** [comment]
@UltraNix either this keeps breaking or it was never applied to live server.
![image](https://github.com/gamefreedomgit/Frostmourne/assets/100322493/4c26055f-603a-493e-8c40-cd9da4805b81)

In an active segment of 51seconds if the ICD is indeed 55seconds it would proc only once and only after 56seconds ( and thts assuming it procs on the first second of the segment)
Im vanishing as soon as the second proc happens to break combat and end the segment
segment = recorded time in the skada
active timer : uptime of the player
reason why uptime of the buff is only 15seconds is because im ending the combat before the 2nd buff ends. but you can see that the Count is 2 (2 procs)
second test here with also vanishing to end combat early.
![image](https://github.com/gamefreedomgit/Frostmourne/assets/100322493/dd24c9af-ba00-4015-b8a8-41c172d2977c)
And third test (all of them are on live production server) i vanished after the 2nd proc dissappeared to end combat 
![image](https://github.com/gamefreedomgit/Frostmourne/assets/100322493/a2e26d6c-ca54-46dd-b77c-466d2db7d0f3)

In the third screenshot you can see x2 procs which is 30sec total uptime of the proc in a total segment of  01:04
If the proc is indeed 55seconds and the procs happen immiditely which is amazing rng then it would require a total of 110 seconds to even consider the 2nd proc happening so 1 minute passes and then 50seconds.
You can even confirm the uptime on the screenshot with small math
64 seconds segment and 30sec uptime which the buff has 46.9% uptime, 64*0.47 = 30.08.
which indicates that it is indeed lower than 55sec icd.

every test leads me to the same conclusion that this is current on live lower icd than my original bug report
![image](https://github.com/gamefreedomgit/Frostmourne/assets/100322493/0a8b805d-9378-4fc2-b4a7-d8d322f08d31)


I have not tested the other two embroideries, but i will do it if need be.

**Comment by UltraNix** [comment]
Fixed.
