### ISSUE TITLE
Feral Charge & Shadow Step on Cannons

### ISSUE THREAD

**Issue by AMInxs** [gamefreedomgit/Frostmourne#788]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Druids and Rogues are able to Shadowstep/Feral Charge Cat onto cannons in Wintergrasp and Strand of the Ancients, bypassing the wall restrictions of the bgs.

**How to reproduce:**
Use the ability on any cannon in WG or SotA.

**How it should work:**
Shouldn't be able to do that.

**Database links:**
https://www.wowhead.com/wotlk/spell=49376/feral-charge-cat#comments
https://www.wowhead.com/wotlk/spell=36554/shadowstep#comments

**Comment by UltraNix** [comment]
Fixed.

**Comment by Acurtis03** [comment]
yo this is not a bug???? wtf this is how these

**Comment by GraveofBears** [comment]
This isn't a bug, yes, Feral's and Rogues were always able to shadowstep and charge to the cannons. There was a bug on classic that prevented us from doing this, it would display "No Path Available", but that was fixed later I think.

The reason that these spells can be used to reach the cannons is because they are a "Leap/teleport" attack and not an attack that requires pathing.

**Comment by UltraNix** [comment]
Fixed.
