### ISSUE TITLE
class related : hunter bug

### ISSUE THREAD

**Issue by Macilious** [gamefreedomgit/Frostmourne#848]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
apparently , sometimes while doing some quests that may require a specific target to submit or secure "whatever you'll name it" , having a pet makes the quest not recognize the process , one example i have encountered , quest called Boiling Point , where you need to force 2 targets to submit, one water and other fire elemental , because my pet as a hunter goes in and taunt while i'm attacking it with range skills , it doesn't count , i have to force the target to move to me , then let the pet attack later after that .

**How to reproduce:**
just simply use hunter and do test it on the quest in borean tundra

**How it should work:**
it shouldn't do that , since pet suppose to be considered part of my character , not another independent character of it's own . and it should count , whether i let the pet in first or not , as long as i attack it with my character too.

**Database links:**

**Comment by PanJanuszek** [comment]
I cannot reproduce your problem with the same steps in Borean Tundra. However...

You are not right. If you don't hit 1dmg to NPC, you won't get exp & loot. That works and it's ok.

In case of these elementals, I had both credits because script requires to beat NPC up to % of his HP. Pet did all job, I didn't engage.

This mechanic is since the beginning of wow, due to bots, exploiters. Read about it here:
https://www.mmo-champion.com/threads/1596745-Pet-only-kills-and-no-exp-rep-loot

Maybe record some movie with situation, which you think it's bug. Please re-open the ticket when you are ready.
