### ISSUE TITLE
Vindication

### ISSUE THREAD

**Issue by Manpower99** [gamefreedomgit/Frostmourne#965]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/wotlk)

**Description:**
Vindication procrate seems to be significantly lower than it should be, you can go for up to 10seconds without proccing it.
Unsure if it should be PPM or % but for a talent of significant importance to tank damage it is currently extremely unreliable.

https://www.wowhead.com/wotlk/spell=26016/vindication

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by WhitemaneIsa** [comment]
It seems to only not be 100% proc on non-abilities, it also only applies 8 instead of 10 seconds if it is triggered by an autoattack instead of an ability, Judgements apply the normal 10 seconds but also not 100%.
Changelog is a little indecisive about whether it should in fact be 100% or not, but Hand Of Reckoning is supposed to proc it 100% and it does.

**Comment by Manpower99** [comment]
> It seems to only not be 100% proc on non-abilities, it also only applies 8 instead of 10 seconds if it is triggered by an autoattack instead of an ability, Judgements apply the normal 10 seconds but also not 100%. Changelog is a little indecisive about whether it should in fact be 100% or not, but Hand Of Reckoning is supposed to proc it 100% and it does.

Yup, confirmed today it is 8seconds if triggered by white hit and if triggered by yellows it is 10seconds.
the proc rate has NOTICABLY improved but still has big downtime sadly.

**Comment by Afgann** [comment]
fixed
