### ISSUE TITLE
Shaman Totem Items

### ISSUE THREAD

**Issue by Aeradel** [gamefreedomgit/Frostmourne#992]
The QoL totem added is destroyable, while the ones that are provided by the quests are not. 

Totems from the quests should be either not given or destroyable and the QoL totem given to shamans should not be able to be destroyed.

**Comment by UltraNix** [comment]
QoL Totem?

**Comment by WhitemaneIsa** [comment]
> QoL Totem?

The Quality of Life Totem is the Totem of the Earthen Ring which is given to all Shamans by default so they do not have to do the quests, I asked Gaga to make it indestructible because people kept throwing it away, but now instead they have the Earthen Ring Totem and the Basic Totems they normally get through questing which are indestructible. The quests should simply not give any Totem IMO as they have the indestructible Totem of the Earthen Ring.

**Comment by UltraNix** [comment]
Fixed.
